### ISSUE TITLE
Confusing phrasing in the ML use case description

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#101]
~~~
Based on https://mailarchive.ietf.org/arch/msg/rats/2rwmcm7pQICXN8lzlX21lEkb9Is/
~~~

>  This typically works by having some protected environment in the
>  device attest to some manufacturer service.  If remote attestation
>  succeeds, then the manufacturer service releases either the model, or
>  a key to decrypt a model the Attester already has in encrypted form,
>  to the requester.
>
>  Attester:  A device desiring to run an ML model to do inferencing
>
>  Relying Party:  A server or service holding ML models it desires to
>  protect

Kathleen's comment: I think it would help to talk about inferences in the written description. For the attester, if it's the whole system as opposed to a component, then then definition makes sense. I'm wondering if it is crisper when narrowed. RoT captures inferences of the ML modeling used as evidence. Does the relying party hold the ML model or knowledge of expected inferences? I'm happy to propose alternative text once I have more information to more fully understand the use case.

**Comment by nedmsmith** [comment]
The existing text treats the model as though it were a file to be accessed and attestation results used to sway an access control decision.

The comment seems to suggest the model is trained to perform Verification. Both might be reasonable use cases, but they shouldn’t be conflated IMO.

**Comment by mcr** [comment]
The ML model is not involved in producing evidence.
The Evidence of trustworthiness is about whether or not the device will be allowed to have the ML model.
"to do inferencing" - removed.
