### ISSUE TITLE
Appendix A: Time Considerations regressions

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/architecture#111]
PR #88 and PR #91 merged text that I had, and continue to have, problems with.

A summary of the problems follows:
1) It includes events (CC, RP) that are not used in any checks in the text.  I had pointed this out before when the PR was generated, but the PR was merged without addressing this comment.
2) The section about using timestamps with synchronized clocks was removed and replaced with a section that talks about a different mechanism (handles) that is not in any RFC or WG document.   I believe that such replacement is inappropriate.  If the WG adopts a document that talks about a handle distribution mechanism, then a section can be added.  Or if there is a standard from another org that can be referenced then it's fine to add one in that case too. But I think it should not replace the section discussing the well known technique of synchronized clocks (e.g., using secure NTP, or PTP (IEEE 1588-2002) or whatever other standard mechanism).
3) time(HD) is problematic as phrased since all the other events are times as seen by a single entity, whereas time(HD) does not clearly say whose perspective (i.e., whose clock) it is from... is it the distributor's?  Text is unclear.
4) It talks about nonces in a timestamp section, which I think causes confusion since there's already a separately section about nonces and this section is labeled to be scoped to timestamps.   Addressing #2 might address this naturally, if it uses a different section title.
5) There are some editorial typos, such as capital "The" in the middle of a sentence, etc.
6) I have no idea what "delta(time(HD),time(EG))distribution-interval" is supposed to mean.   Normally I would expect an equality for any condition to be evaluated, but I have no idea what this check is.
7) time(HD) and time(EG) are according to different clocks (if my guess about point 3 above is right) and so the delta is not directly comparable.  I'm not sure how point 6 accounts for this.
8) The phrase "A nonce not predictable to an Attester (recentness & uniqueness) is sent to an Attester" has "(recentness & uniqueness)" which doesn't read well (sounds like bad grammar) to me, and is not explained.

**Comment by henkbirkholz** [comment]
Hopefully PR #123 now addresses this issue.

**Comment by dthaler** [comment]
PR #125 reverts the text, leaving the work in progress in PR #111

**Comment by mcr** [comment]
fixed by #145.
