### ISSUE TITLE
more privacy considerations

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#116]
Kathleen's review [part 2](https://mailarchive.ietf.org/arch/msg/rats/7-UJAqHPMLhrGCk9tyh3JqGu8rw/)

Further privacy considerations:
* Remote attestation also provides a way to profile systems as well as the user behind that system.
* If attestation results go higher in the stack to include containers and applications, it could reveal even more about a system or user.
* The scope of access needs to be emphasized, including the administrators access to data (or restrictions).
* If there is a way to make inferences about attestations from their processing, that should be noted as well.

**Comment by mcr** [comment]
Pull request #129 tries to start.
