### ISSUE TITLE
Trust of Attester by Verifier is transitive

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#132]
This is for section 7.2 on Attester, 7.4 on Verifier and 7.5 the Endorser/Manufacturer.

The main trust flow for all of attestation is that the Verifier has a direct trust relationship with the Endorser/Manufacturer but not the Attester. The Endorser/Manufacturer supplies Input (e.g., an Endorsement containing key material) to the Verifier that allows the Verifier to come to trust the Attester. 

In just about every use of attestation, there is no direct trust of the Attester by the Verifier. The Verifier doesn't directly trust the Attester's HW or SW as suggested by the text in 7.4. This text seems incorrect on one of the most fundamental attestation concepts.

Section 7.2 and 7.5 don't even discuss the primary transitive trust flow. They only address the secondary trust flow on confidentiality and privacy. While confidentiality and privacy are important they are not the primary reason that the Attester and Endorser exist.

**Comment by mcr** [comment]
closed by #154.
