### ISSUE TITLE
Clarify applicability of attestation vs HTTPS/TLS

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#134]
Reviewing the trust relationships described in the architecture document got me thinking about sharpening a distinction between device attestation (e.g., EAT for phone) and service authenticity (e.g. HTTPS for a web site):

**Device Attestation**

- Focus is on the implementation, the HW and SW
- The legal entity of interest is the device manufacturer
- The claims are about the HW and the SW, not the device owner
- Example: a mobile phone (not its owner/user)
- Example: integrity of a remote device

**Service Authenticity**

- Focus is on the provider of the service, not the HW or SW
- The legal entity of interest is the service provider
- There is no equivalent of claims, but if there was they would be about the business or person operating the service
- Example: a web site
- Example: an email provider (IMAP service)

Service providers (e.g., web sites) use whatever HW and SW they want to use. As a user of the service we don’t care what HW and SW they select. We trust the service provider to pick good HW and SW and to configure and operate it correctly. They might change the HW and the SW and as a user we won’t know.  For example we trust Bank of Xxx to operate their banking web site correctly with little concern for their HW. This is why attestation of the HW and SW is not so useful to the user of a service.

Users of mobile phones and IoT devices are not trustworthy to pick secure HW and SW. They are not professionals like the people running web sites. There is little accountability against them if they pick bad SW and HW. Therefor we want attestation for these usage scenarios. This is why EAT, FIDO and Android Attestation exist.

I don’t think the line between device attestation and service authenticity is completely black and white. In some use cases attestation may be bent to provide some service authenticity. But I don’t think it makes sense to add attestation to the millions of web sites out there, add support for it to browsers and make attestation an extra layer of security for web browsing.

I think it is fine for a service provider to use attestation inside their service to monitor integrity and such of the HW and SW providing the service. But usually that won’t be manifest outside the service. It could be awkward for the user to the service to have to re evaluate the service every time the service provider changes HW.

Another way to look at this is from a certification / regulatory view. If the thing you're looking at is a candidate for implementation certification such as Common Criteria, FIPS, FIDO certification, then it probably lines up with device attestation. On the other hand, if the thing your are looking at lines up with regulation (e.g., banking regulation, GDPR,...) and to some degree OWASP, then it probably lines up with service authenticity. 

I think the RATS architecture document should probably have text that describes when attestation is applicable and when it is not, for example saying something like “attestation is not a replacement or augmentation for HTTPS/TLS"

**Comment by henkbirkholz** [comment]
In the last editors session, the editor's rough consensus was that https does not provide the authenticity but it provides a secure channel. Instead, authenticity is checked via successful authentication rooted in identity documents (I hope I captured appropriately, please bash).

Taking that into account, how does this effect this issue?

Looking at the last paragraph, "Remote attestation procedures are not a replacement for secure authentication, they are based on secure authentication." might be missing vital parts. Does anything need to be added or modified here?

**Comment by laurencelundblade** [comment]
Note that #153 is INCORRECTLY referenced here. Is the resolution of a different issue about HTTPS vs Attestation.

**Comment by laurencelundblade** [comment]
I think comments from @henkbirkholz do need to be taken into account when the text to address this issue is written.  My text in opening the issue is not intended as the text to resolve the issue.

Probably the text that resolves the issue needs to refer to "HTTPS plus the web certificate infrastructure that includes public CA's and browsers and/or private CA's used in B-to-B..." or such.

**Comment by mcr** [comment]
I think the RATS architecture document should probably have text that describes 
    when attestation is applicable and when it is not, for example saying something like 
    “attestation is not a replacement or augmentation for HTTPS/TLS"

The design team disagrees with this.  Every authentication (including HTTPS) can be said in terms of attestation.  It is the verifier that allows the decoupling of the RP to know the expected state of the Attester.
