### ISSUE TITLE
introduce term "measure" 

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#14]
Ned suggests that the term Measure be added to connect the Attested Environment and Attesting Environment.  
There may be multiple Attested Environments that can measured by a single Attesting Environment (such as when there is a TPM, SGX, DICE).

**Comment by mcr** [comment]
There may be multiple Attested Environments that can measured by multiple Attesting Environment (DICE == TCG standard for generating layered claim sets).

**Comment by mcr** [comment]
Discussion about combining the two environments together leads to comments about having measuring code in ROM, and then this leads to discussion about having a Manufacturing Certificate. 
Issuing a manufacturing certificate is an operational way to keep the attesting environment separate from the attested environment.

**Comment by mcr** [comment]
"attesting" and "attested" are too alliteratively similar.
"measure" is the process.
"measuring environment"... discussed.
"surveyor" is suggested.  MW: implies that they are actively "going out" and doing it.

**Comment by mcr** [comment]
https://www.thesaurus.com/browse/survey?s=t

**Comment by laurencelundblade** [comment]
Pretty sure "measurement" is taken to mean hashing some bytes of memory, a file or such for later comparison to expected values. Lots of claims are not of that nature, so I'm not so much in favor of this term.

**Comment by William-PanWei** [comment]
I find that "Claim" is also widely mentioned/used but not yet defined in Terminology. This term may also need to be considered to be introduced in Terminology.

Usage examples:
The “attester” produces a set of “claims” about a “target”. The claims are known as “attestation evidence”. (From Laurence's email)
Claim:  A statement about the construction, composition, validation or behavior of an Entity that affects trustworthiness.  Evidence, Reference Values and Attestation Results are expressions that consists of one or more Claims. (From draft-birkholz-rats-architecture)
The evidence is typically a set of claims about its software and hardware platform. (From )

**Comment by mcr** [comment]
Laurence Lundblade <notifications@github.com> wrote:
    > Pretty sure "measurement" is taken to mean hashing some bytes of memory, a
    > file or such for later comparison to expected values. Lots of claims are not
    > of that nature, so I'm not so much in favor of this term.

I believe that the term measurement was used rather than the term "hash"(ing),
because not all evidence is in the form of a hash.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by laurencelundblade** [comment]
The term "claim" is somewhat inherited from JWT/CWT, but agree we need a definition here in RATS. Seems more like "claim: is an individual chunk of data about a target; the attestation evidence and attestation result is primarily made up of claims".

Still don't like the term measurement. I don't think a SW Version, HW Version a GPS  location, a public key, most of COSWID and such are measurements.

**Comment by nedmsmith** [comment]
+1

“Claim” inherits baggage from elsewhere. There has been several threads about alternatives (e.g. “assertions”) as well. Given people are OK with its use, terminology section should include a definition.

Arch also determined it is correct to use “assertion” generically to describe interactions between Roles. Claim has more specific context but it needs a definition so we can be on the same page about what that context is.

**Comment by nedmsmith** [comment]
TCG use of the term ‘measure’ isn’t limited to hashing. The RIV draft / architecture / use case is heavily focused on inspecting SW/FW modules using hashing so it can come across as though that is the only interpretation.

The important relevance is that ‘measuring’ is something that happens before ‘attesting’ (signing). Measuring could happen by an environment that is different from the ‘attesting environment’.  However, the trust model semantics equate them as being equal, therefore for convenience and simplicity it is OK to avoid introducing another term.

**Comment by mcr** [comment]
The terms "collect" and "record" are also suggested.
  --> "record the values of claims"...  "audit log"
  --> **"collect the values of claims"**

HB: Claims are name/value pairs.. but not only this way. Are this way in JWT/CWT, but not in certificates.  
DT: Certificates are extension ID and and value, why isn't it the same?  So, it's the "name" part which is wrong, so maybe it is ID/value pair?

We should have a definition of claim, in the generic sense.
The semantic meaning may be implied.
We can not always find names without colliding, and we can't always invent new names.
