### ISSUE TITLE
Endorsements definition is too narrow given PR150 clarification

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#151]
Since PR150 clarifies the difference between reference values and endorsements. It seems more clear that endorsements describe properties of the Attesting Environment (which includes creation / signing of Evidence) and therefore describes "signing capability". However, Attesting Environments also collect claims securely. Therefore, the current definition of Endorsements is still too narrow. 

Suggested text: "Endorsement:  A secure statement that some entity (typically a manufacturer) vouches for the integrity of an Attesting Environment's various capabilities such as Claims collection and Evidence signing"

**Comment by laurencelundblade** [comment]
Definitely agree that the separation of Ref Vals makes the nature of Endorsements much more clear in the way Ned suggests.  Now they are primarily attestation keys and implicit claims which both describe the Attester.

However, I think the one-liner definition of Endorsement should stay as is and further description should go in the Endorsements section in the Conceptual Messages section.

I also think Endorsements should always be described as being produced by an Endorser. Then the Endorser is sometimes a manufacturer.

It should be mentioned that Endorsements can contain implicit claims (in the Endorsements section, not the one-liner definition).

**Comment by nedmsmith** [comment]
I don’t think we have a clear definition for ‘implicit claims’. While I agree Endorsements are likely to be implicit claims, it isn’t clear that a Reference Values Provider (RVP) couldn’t also supply implicit claims. This become a consideration given we’ve narrowed the scope of what an Endorser can say. This is the risk we take when trying to be too specific about the roles / messages in an architecture. It is sometimes better to allow wording that can be interpreted broadly then include specific examples.

**Comment by henkbirkholz** [comment]
So we started to use the following phrase/concept:

Claims in Endorsements "vouch for" characteristics of an Attesting Environment, which an Attester cannot create Evidence for. As a contributor I think "vouching for" reads significant more intuitive than "implicit".

Does anyone disagree with that?

Do we need to add explicit text that spells out these semantics?

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
