### ISSUE TITLE
Endorser / Endorsement optional optimization?

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#158]
Dave pretty clearly thinks of Endorsements and the Endorser as an optional optimization in an attestation deployment.  Also, the Endorser is an Entity like a Verifier Owner, not a Role, like a Verifier. Most of the text in the document is consistent with this. For example, it says "...help Verifier...".

The other messages in the document, the Attestation Evidence and Attestation Result, are not optional, though Attestation Result can be a bit virtual when Verifier and RP are the same Entity. We don't say clearly that Endorsements are optional. Probably we should say so (if we really do agree they are optional).

Personally, I think it is confusing that Endorser and Endorsements, that are optional helper optimizations, are featured so prominently in Figure 1.

**Comment by nedmsmith** [comment]
Creation of 'reference value provider' and cleanup that qualifies these as roles performed by an entity seems to clarify the concerns raised.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
