### ISSUE TITLE
Endorsements should be confidential when carrying symmetric keys

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#162]
There should be a comment, probably in security considerations, that Endorsements should have confidentiality protection when carrying symmetric verification keys.

This seems in line with the level of concern for security in the rest of the document in UCCS and such.

**Comment by mcr** [comment]
Discussion thread at https://mailarchive.ietf.org/arch/msg/rats/d1iJn43H1fRtnWmCvKDE7l4ar3E
