### ISSUE TITLE
Talk about how the efficacy of Attestation Results depends on the Attesting Environment

### ISSUE THREAD

**Issue by ericvoit** [ietf-rats-wg/architecture#166]
From https://mailarchive.ietf.org/arch/msg/rats/m65COAszSM7HfqL6O6ciw5AJVVk/

    Section  4:  General Comment  (this comment could also apply to Section 12)
    It is up to the Relying Party to evaluate the Verifier.  And not all
    Verifiers should be seen as equivalently trustworthy.  Additionally, any
    particular Verifier might be able to provide a consistent level of certainty
    in the "Attestation Results".  This is because the capabilities of the
    Attesting Environment will vary.   This section does not hint at the varying
    levels of certainty in the "Attestation Results" based on the varying
    quality and quantity of available Evidence of different types of Attesters.
    I am not sure if this truism belongs in this section.  Or if this truism
    belongs in the document at all.  But without having this nuance being
    described somewhere, it could leave the perception of a higher level of
    confidence in the Appraisals being from a deployable RATS architecture made
    than might necessarily be warranted.    Note that this issue is also alluded
    to in Section 7.4 and Section 12.  But neither address things like whether
    Attestation Result values should provide a minimum level of confidence
    regardless of the type of Attester being evaluated.
    In the end, I am fine if nothing changes in the document as a result of this
    comment, but I wanted to have the authors consider whether this is worth a
    statement or two.

**Comment by mcr** [comment]
Need reference to Common Citeria, public citation.

**Comment by mcr** [comment]
fixed in commit d1953d98337b709f33ff81420366f298895cd0f5
