### ISSUE TITLE
Evidence definition (from Guy)

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#172]
````
   Evidence:  A set of information about an Attester that is to be
      appraised by a Verifier.  Evidence may include configuration data,
      measurements, telemetry, or inferences.
````

What’s the difference between claim and evidence?
Maybe you start with a Claim, then sign it and that makes it into Evidence?

Is Evidence a ‘set of claims’?  
[and what’s the difference between a ‘set of information’ and ‘information’?]

**Comment by dthaler** [comment]
Maybe "A set of signed Claims about an Attester..."?
