### ISSUE TITLE
Definition of Relying Party in confidential ML model use case

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#177]
section 3.1

````
   Relying Party:  A server or service holding ML models it desires to
      protect
````

It would be easy if it was simply Protecting – Just say No! 😊  I think you mean that the relying party wants to release the object only to authorized users.

**Comment by William-PanWei** [comment]
The relying party holds the confidential ML models, so it needs to protect the models. Authorizing the users before releasing the models is one method used to protect the models. Protecting is a broader goal of the Relying Party. So I think the current description is OK to explain what the Relying Party is in this use case.

**Comment by William-PanWei** [comment]
I suggest "wontfix" this issue.

**Comment by dthaler** [comment]
Agree with William.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
