### ISSUE TITLE
3.3 Confidential Data Retrieval

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#178]
“Retrieval” by whom?  I think you mean something like “conditional Release of Confidential Data”

**Comment by William-PanWei** [comment]
Section 3.3 "Confidential Data Retrieval" is relevant to section 3.2 "Confidential Machine Learning (ML) Model Protection". These two use cases are similar. I suggest changing the title of section 3.3 to "Confidential Data Protection".
