### ISSUE TITLE
Claim is used heavily but not in the terminology section

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#18]

**Comment by laurencelundblade** [comment]
I think we must define claim in the terminology section.

The term claim originates from JWT, but JWT doesn't really define it.

**Comment by dthaler** [comment]
The fact that "claim" is used throughout both RFC 7519 (JWT) and RFC 8392 (CWT) without any formal definition, means that it's clearly ok to have an RFC that does not define claim in its terminology section or anywhere else.   I would favor following those precedents and not trying to retroactively invent some definition we have to agree on.

**Comment by henkbirkholz** [comment]
https://tools.ietf.org/html/rfc7519 defines Claim as:

   Claim
      A piece of information asserted about a subject.  A claim is
      represented as a name/value pair consisting of a Claim Name and a
      Claim Value.

**Comment by mcr** [comment]
If the term is defined elsewhere, is that definition used consistently with ours?

Claim  
A piece of information asserted about a subject. 
A claim is represented as a name/value pair consisting of a Claim Name and a Claim Value.  
https://tools.ietf.org/html/rfc7519

Claim:
: A piece of information asserted about a subject. (consistently with {{RFC7519}})
A claim is usually represented by as a name/value pair.
