### ISSUE TITLE
TAM/TEE use case

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#181]
````
The TEE conducts a
   remote attestation procedure with the TAM
````
It’s the TAM that’s doing the conducting, no?

**Comment by dthaler** [comment]
The TEE is the Attester, and in the current TEEP transport spec, the TEE initiates communication. So I would say "no".

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
