### ISSUE TITLE
FIDO Biometric Authentication definitions

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#184]
````
   Relying Party:  Any web site, mobile application back end or service
      that does biometric authentication.
````

It sounds like the Verifier “does” the authentication, and the relying party relies on the answer?

**Comment by thomas-fossati** [comment]
Besides, there's a slight imprecision here: the web site / mobile app backend service don't do biometric auth.  Instead, the authenticator binds biometric info to crypto material so that the web site can deal with usual crypto auth.

**Comment by henkbirkholz** [comment]
For context, this is https://ietf-rats-wg.github.io/architecture/draft-ietf-rats-architecture.html#section-2.7

How about:

> Relying Party: Any web site, mobile application back-end, or service that relies on digestible authentication data based on biometric information.
