### ISSUE TITLE
Entity and Sub-Entity & Composite Device and Component

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#19]
Taking into account the recent trends in terminology used in draft text & PR, I am proposing to add Entity and Sub-Entity to the terminology section. We do not need to over-specify here. Hence, only mentioning Composite Device and Components as an examplew for each of the terms in the definition text could be enough.

Are there any objections to this proposal? If not, we could create a PR and address it in next week's meeting.

**Comment by nedmsmith** [comment]
Agree so long as it is understood that other words can be used in place of entity when they add context for readability such as component, sub-component, device, environment and so forth.

**Comment by henkbirkholz** [comment]
This now relates to the comments on #77
