### ISSUE TITLE
4.4 how does loader environment work

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#192]
````
       |   .---------------|-----------.    |    |
           |   | Target        v           |    |    |
           |   | Environment .-----------. |    |    |
           |   | B           | Attesting | |    |    |
           |   |             |Environment|-----------'

````

The loader environment only exists for a second or two, and has few resources… how it is supposed to report evidence to a verifier in that window?

**Comment by mcr** [comment]
Refers to figure 3, in section 3.4, on layered attestation.

**Comment by henkbirkholz** [comment]
It is rare that early layers generate or convey Evidence. In critical system with appropriate protected capabilities that actually happens. I can see that it is not a common case and would not argue strongly against removing 'B' from that conveyance arc.

**Comment by dthaler** [comment]
Perhaps a better example for which the loader environment is not ephemeral would be where B is the OS and C is an application/workload process.
