### ISSUE TITLE
4.5 Composite Device

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#194]
Should this section include an Informative Reference to the Trusted Computing Group “Guidance for Securing Network Equipment”
https://trustedcomputinggroup.org/wp-content/uploads/TCG_Guidance_for_Securing_NetEq_1_0r29.pdf
  It seems to repeat more or less the same thing, but using the RATS lexicon

**Comment by thomas-fossati** [comment]
Another comment I have on this section is about the the trust model of a composite device: it looks like the lead attester needs to be trusted to collect the most fresh evidence from the other slots?  Is this discussed anywhere?

**Comment by William-PanWei** [comment]
> Another comment I have on this section is about the trust model of a composite device: it looks like the lead attester needs to be trusted to collect the most fresh evidence from the other slots? Is this discussed anywhere?

Who do you mean the lead Attester needs to be trusted by? The Verifier/Relying Party or other slots/Attesters?
The collecting capability is one of the characteristics the lead Attester has. So after the Verifier verifies the Evidence of the lead Attester successfully, it can trust the lead Attester's collecting capability.
The Evidence of other slots are signed by these slots themselves, and these slots can send Evidence to the lead Attester just as the lead Attester sends Evidence to the on-path router to the Verifier.

**Comment by thomas-fossati** [comment]
> Who do you mean the lead Attester needs to be trusted by? The Verifier/Relying Party or other slots/Attesters?

I meant the latter - apologies for the lack of precision.  In particular, I am interested in the scenario where a compromised lead that has cached some previously collected evidences, can forward those instead of fresh slots' attestations.
