### ISSUE TITLE
Handles appendix needs some care

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#198]
The appendix on Handles needs some work to better clarify the concepts and simplify the flow.

Some things about the text:

* Clearly define what is a handle;
* Explain its relation with epoch establishment;
* Clarify network jitter impact on handle validity;
* Explain what are the base rules for working with handles;

Some further points on the sequence diagram:

* Fix confusing legend;
* Add some accompanying prose to explain the depicted use case as it's not self-evident;

**Comment by thomas-fossati** [comment]
WIP text at https://hackmd.io/KVGaui6IRAS6RjIS2_JtKA
