### ISSUE TITLE
Target should be defined in terminology section

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#20]

**Comment by dthaler** [comment]
Not sure that I agree with the issue subject line.  Please provide justification in description/comments in this issue.

**Comment by mcr** [comment]
Proposal is that "Two Types of Environments" to have a diagram to explain things.
Feeling is that we don't need to put these into the terminology section, as we use that term only in section 4.1.

**Comment by mcr** [comment]
closed by #68.
