### ISSUE TITLE
5.1 - password model, evaluation of evidence

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#203]
````
The format of the Evidence on the other hand is only
   constrained by the Attester-Verifier remote attestation protocol.
````

Yes but for real passports, the Relying Party must separately evaluate the trustworthiness of 192 different Verifiers, i.e., nation states, no?  This seems to imply that relying parties had better get ready to validate a limitless variety of Attestation Results?

[mcr: yes, in fact, in real passports, Relying Parties do not treat all 192 nation states equally, which is why, I'm told, Israeli Mossad agents apprently like Canadian passports...]

**Comment by William-PanWei** [comment]
The detail of how the Relying Party should trust the Verifiers is described in the "Trust Model" Section. Besides, there may be  Appraisal Policies for Attestation Results, which will guide the Relying Party on validating the Attestation Results.
I don't think an update is needed here.

**Comment by henkbirkholz** [comment]
The passport analogy show that there is a:

Individual (1)<--Evidence-->(1) Passport Agency
Individual (1)<--Attestation Result -->(N) Immigration Desk

The text currently does not state that this implies that interoperability and standardization is more relevant for Attestation Results than it is for Evidence (in this model).

The question I want to raise is, do we want to make that more explicit to the reader?
