### ISSUE TITLE
5.2 background-check model plumbing

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#204]
````
The resource access protocol between the Attester and Relying Party
   includes Evidence rather than an Attestation Result, but that
   Evidence is not processed by the Relying Party.  
````

I’ve never understood why the plumbing of passing evidence through the Relying Party without analysis to the Verifier was a part of this model.
Plumbing aside, it’s the verifier that collects and analyses the evidence, generating a Result to send to the Relying Party, isn’t it?

If we really are comparing with the Background Check procedure, I think the relying party (the employer) usually contracts an agency (the verifier) to collect evidence from the attester (the prospective employee), i.e., the relying party does not act as a pass-through, and may not be allowed to see all the evidence anyway.

**Comment by William-PanWei** [comment]
About the Background Check Model, I think it is also reasonable and possible. For example, in a medical insurance claim scenario, the insurance applicant (Attester) submits an invoice (Evidence) issued by the hospital to the insurance company (RP), and the insurance company (RP) sends the invoice to the hospital (Verifier) to verify its authenticity.

**Comment by William-PanWei** [comment]
````
5.  Topological Models

   Figure 1 shows a basic model for communication between an Attester, a
   Verifier, and a Relying Party.  The Attester conveys its Evidence to
   the Verifier for appraisal, and the Relying Party gets the
   Attestation Result from the Verifier.  There are multiple other
   possible models.  This section includes some reference models.  This
   is not intended to be a restrictive list, and other variations may
   exist.
````
About the model in Guy's comment, I think this paragraph briefly describes the model.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
