### ISSUE TITLE
6.: isolation

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#207]
````
The entity, as a system bus Verifier, may choose to fully
   isolate its role as a wide-area network Attester.

````

Isolate?  From what?

“Isolation” seems to be used several times in this and later sections without saying who’s isolating what from whom.

**Comment by dthaler** [comment]
I don't understand that sentence either.  Propose removing it.

Another sentence:

> Implementers need to pay close attention to the isolation and protection of the
> Attester and the factory processes for provisioning the Attestation key material.

Propose removing "isolation and"

Other uses of isolation I think are fine, where it means that an Attesting Environment cannot be modified by a Target Environment it measures.   Any way of protecting that might be called "isolating" the two environments from each other in some way.

Other uses of
