### ISSUE TITLE
7.2 -- Attester

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#208]
````
In some cases where Evidence contains sensitive information, an
   Attester might even require that a Verifier first go through a TLS
   authentication or a remote attestation procedure with it before the
   Attester will send the sensitive Evidence.  _This can be done by
   having the Attester first act as a Verifier/Relying Party, and the
   Verifier act as its own Attester, as discussed above._
````

I don’t know what it means, but all the cases here seem to ultimately rely on a unitary Verifier/Relying-Party somewhere in the chain.

Maybe that’s not true…  if the verifier and relying party trust each other by fiat, the roles need not be combined.

**Comment by dthaler** [comment]
It means mutual attestation.   Say you have devices A (normally an Attester) and V (normally a Verifier) and RP (normally a Relying Party).   A can say it won't send Evidence to V unless V first attests to A.   Thus, A starts by acting as a Relying Party where V is the Attester.  If A devices that V is trustworthy, then A can start sending sensitive Evidence to V.

Note this does not require anywhere have a combined Verifier/Relying Party.

**Comment by henkbirkholz** [comment]
I can see how:
* "Verifier/Relying Party" looks misleading here
* Dave illustrated well that this text is not about a "unitary Verifier/Relying-Party"
* this is related to the current mutual authentication/attestation discussion that recently emerged

I'll try to pitch this issues in the next meeting so we can deal with it in the same swoop as mutual authentication. Personally, I'd simply leave the text as is.

**Comment by mcr** [comment]
reference #268

**Comment by mcr** [comment]
closed with email: https://mailarchive.ietf.org/arch/msg/rats/e0QYhqWO0MxmZHWx654AB5vrHtw

**Comment by dthaler** [comment]
Closing since Michael's comment above says "closed with email" but didn't actually close the issue
