### ISSUE TITLE
7.4 Verifier

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#210]
````
   That is, it might appraise the trustworthiness of an application
   component, operating system component, or service under the
   assumption that information provided about it by the lower-layer
   firmware or software is true.  A stronger level of assurance of
   security comes when information can be vouched for by hardware or by
   ROM code, especially if such hardware is physically resistant to
````

How does this, for example, impact RATS?
Does RATS include a way to express all these variations, or is it just saying there are a whole lot of assumptions that can be made in determining what to trust?

**Comment by nedmsmith** [comment]
My assessment of the entire section 7.4 is that it says very little about what a Verifier is or does. There existing text seems to focus on giving advice about the different aspects of what it means to trust different entities that may be performing the various roles in the attestation architecture. Certainly, the verifier is the most complex of all the roles with 4 inputs and one output message. And we have made an architectural decision to put the complexity in the Verifier generally. It seems to do this in a way that makes it clear, the section should be broken into smaller parts. For example, a sub section for each input / output message type. There are some basic sequence of operations too, such as verifying signature, decoding of messages, discovering and assembling all the context needed before appraisal can start. Then there is appraisal processing. What constitutes a match between Evidence claims and Reference Value claims etc. 

But if the objective of the section is to just talk about what the semantics of 'trust' are, maybe it achieves that goal already. Though it doesn't do a great job of laying out that that is the goal.

**Comment by mcr** [comment]
Splitting it up into smaller pieces may be reasonable.

But, this is an architecture document: we need to define the inputs and outputs of the Verifier (functional requirements).
We don't need to write design requirements!  

The whole point of hiding all the complexity in the Verifier is so that we can intelligently explain the protocols in/out of it, and drive standardization (commodification) of the Attester.   This is classic CS "add a layer of indirection"
Secondarily, the RP role should become simpler, but as the X diagram implies, the RP also gets to push complexity to the Verifier.  
If the WG is unhappy with this, then I think that the WG should start a document providing a deeper analysis of the Verifier.
This is consistent with #162.

**Comment by mcr** [comment]
email thread started at: https://mailarchive.ietf.org/arch/msg/rats/t2OCsfwQ5ivPScqgO2mN0nlGvL8
