### ISSUE TITLE
7.4 Verifier - key material

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#211]
````
  The manufacturer of the Attester arranges for its Attesting
   Environment to be provisioned with key material.  The key material is
   typically in the form of an asymmetric key pair (e.g., an RSA or
   ECDSA private key and a manufacturer-signed IDevID certificate)
   secured in the Attester.
````

1) Is this a normative statement?

2) I think the next paragraph says that maybe it’s not an asymmetric key, and anyways, keys are out of scope for RATS Arch

**Comment by nedmsmith** [comment]
In a layered device architecture the previous layer "provisions" the next layer. Hence, it isn't possible for the 'manufacturer' entity to do that. I don't know why a section on "Verifier" is going into so much detail about the Attester.
