### ISSUE TITLE
7.4 Verifier unsigned CBOR

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#212]
````
  A conveyance protocol that provides authentication and integrity
   protection can be used to convey unprotected Evidence, assuming the
  
````

I assume this is an escape hatch for unsigned CBOR.
But I’m not sure the sentence makes sense…  if the conveyance protocol provides protection, then it’s not unprotected evidence?
Or is there some other point we’re trying to get at?

**Comment by nedmsmith** [comment]
"...used to convey Evidence that is otherwise unprotected, relies on the conveyance protocol for the following protections:
   1. ..."

**Comment by William-PanWei** [comment]
````
I assume this is an escape hatch for unsigned CBOR.
````
I think unsigned CBOR (the UCCS draft) is one example of "unprotected Evidence". Maybe we can add a reference pointing to the UCCS draft.

**Comment by William-PanWei** [comment]
````
But I’m not sure the sentence makes sense… if the conveyance protocol provides protection, then it’s not unprotected evidence?
````
Maybe we can say "...used to convey Evidence that is otherwise unprotected itself", or "...used to convey Evidence that is otherwise not signed itself"?
