### ISSUE TITLE
8.2 Endorsements

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#213]
````
   However, while an appraisal policy that treats all devices from a
   given manufacturer the same may be appropriate for some use cases, it
   would be inappropriate to use such an appraisal policy as the sole
   means of authorization for use cases that wish to constrain _which_
   compliant devices are considered authorized for some purpose.  For
   example, an enterprise using remote attestation for Network Endpoint
   Assessment may not wish to let every healthy laptop from the same
   manufacturer onto the network, but instead only want to let devices
   that it legally owns onto the network.  Thus, an Endorsement may be
   helpful information in authenticating information about a device, but
   is not necessarily sufficient to authorize access to resources which
   may need device-specific information such as a public key for the
   device or component or user on the device.
````

I think what you mean is that proof of identity and attestation of software integrity are (OMG) not the same thing??
Or is there a more subtle point?

**Comment by nedmsmith** [comment]
What is the issue here?

**Comment by William-PanWei** [comment]
````
I think what you mean is that proof of identity and attestation of software integrity are (OMG) not the same thing??
````
I don't think so. This paragraph highlights that you may need different appraisal policies for the devices from the same manufacturer or even the same type of devices.
For example, one enterprise may buy some Apple laptops, but it doesn't mean all Apple laptops can access the enterprise network. So an appraisal policy that allows all healthy Apple laptops (having the valid certificated signed by Apple and pass the attestation of software integrity) to access isn't appropriate.

**Comment by William-PanWei** [comment]
I don't see an issue here.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
