### ISSUE TITLE
8.3 Attestation Results

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#214]
````
Attestation Results are the input used by the Relying Party to decide
   the extent to which it will trust a particular Attester, and allow it
   to access some data or perform some operation.  Attestation Results
   may be a Boolean simply indicating compliance or non-compliance with
   a Verifier's appraisal policy, _or a rich set of Claims about the
   Attester, against which the Relying Party applies its Appraisal
   Policy for Attestation Results._
````

In this case, what’s the benefit of designating a Relying Party as separate from a verifier?  The first verifier is digesting evidence to create different evidence to give to the next verifier, which has a built-in implicitly-trusted relying party?

**Comment by nedmsmith** [comment]
The AR Claims likely are different from Evidence Claims. The Verifier determines that the Attester is "Trusted" for some definition of trust. Then maps to a Relying Party specific implication - for example access authorization. An example of a non-binary authorization is an OAuth2 token. If a RATS verifier were integrated into an OAuth2 AS, then the Attestation Result might easily be an OAuth2 token.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
