### ISSUE TITLE
8.3 Attestation Results - authorization

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#215]
````
he passport model) or a Relying Party (in the background-check
   model) to indicate that the _Attester should not be treated as
   authorized_ and may be in need of remediation.  In some cases, it may
   even indicate that the Evidence itself cannot be authenticated as
   being correct.
````

Is there a different way to say this?  I assume in Passport, we’re not relying on the Attester to report itself as untrustworthy?
I think it’s more that it doesn’t get a passport, so it has nothing to hand the dude at the immigration desk?  i.e. untrustworthiness is indicated by lack of a passport?

**Comment by nedmsmith** [comment]
The paragraph should begin with "An Attestation Result that indicates ..."
The Relying Party is *always* the entity / role that consumes the Attestation Result. The text that describes the Attester (in the passport model) technically violates the role interaction model. 

Instead, the refusal on behalf of an Attester (acting as a proxy for the Attestation Result) to convey the AR is a protocol or interaction break down scenario. And yes it is correct for the Relying Party to, by default, assume that lack of receipt of an Attestation Result means the Attester is presumed to be non-compliant. 

If the paragraph stated this simply up front then we can avoid dove tailing it into the description of what constitutes non-compliance behavior. For example, paragraph 2 could start differently:
"By default the Relying Party assumes the Attester does not comply with Verifier appraisals. Upon receipt of an authentic Attestation Result and given the Appraisal Policy for Relying Party is satisfied. The Attester's state of compliance changes to be in compliance and actions consistent with compliance may be applied. If the Appraisal Policy for Relying Party is not satisfied, actions consistent with non-compliance may be applied. For example, the Attester may require remediation and re-configuration or simply may be denied further access."

The third paragraph seems redundant to this (and somewhat wordy).
