### ISSUE TITLE
12.1 Attester/Attestation Key Protection

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#218]
````
   Implementers need to pay close attention to the _isolation_ and
   protection of the Attester and the factory processes for provisioning
   the _Attestation Key Material_.  When either of these are compromised,
   the remote attestation becomes worthless because the attacker can
   forge Evidence.
````

What does isolation mean in this context?
Do you need to be explicit about requirements for the keys that go into each device vs the keys used to sign p

Does this include both identity keys and attestation evidence signing keys?

**Comment by nedmsmith** [comment]
The concept is that the Attester function and the data objects it controls (aka keys) must be domain isolated. Wiki offers a definition for domain https://en.wikipedia.org/wiki/Domain that includes a software engineering context. This  use of domain is in the context of a 'protection domain' which isn't defined by wiki or IETF. https://datatracker.ietf.org/doc/rfc4949/ does define domain / security domain. 

We're saying that a protection domain is a IETF security domain where the properties of protection are known or enumerateable. 

A protection domain has the properties:
- isolation - the Attester (Attesting Environment) can't be observed or tampered with such that the Claims it authorizes can be altered. And the Claims is collects can't be misrepresented by the Target Env.

**Comment by mcr** [comment]
> The concept is that the Attester function and the data objects it controls (aka keys) must be domain isolated. Wiki offers a definition for domain https://en.wikipedia.org/wiki/Domain that includes a software engineering context. This use of domain is in the context of a 'protection domain' which isn't defined by wiki or IETF. https://datatracker.ietf.org/doc/rfc4949/ does define domain / security domain.

Okay, but I don't know what to do with this.  Do we change anything?

**Comment by mcr** [comment]
In the text, this now says "protection", so I am closing this issue.
