### ISSUE TITLE
12.1.2 Attestation Key Provisioning Process

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#221]
It seems that all that’s relevant to RATS is “if the key is generated externally, the manufacturer needs to take care to protect it with measures consistent with its value”

````
   Another way to provision the key material is to generate it on the
   device and export the verification key.  If public key cryptography
   is being used, then only integrity
````
This case does seem different – there is simply no known way to extract the key.

**Comment by nedmsmith** [comment]
I agree with MCR's summary that “if the key is generated externally, the manufacturer needs to take care to protect it with measures consistent with its value”. Can we replace the bulk of section 12.1.2 with this single sentence? 
The expectation is that private keys can't be extracted (read) once provisioned. That should be a stated security assumption.  This section reads like a tutorial or primer. That isn't the goal IMO. Security Considerations should state our our security assumptions.

**Comment by mcr** [comment]
{not my comment. Guy's.  If you like that part, generate a pull request please!}
