### ISSUE TITLE
12.2 Integrity Protection

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#222]
````
It is also important that the appraisal policy was itself obtained
   securely.  As such, if appraisal policies for a Relying Party or for
   a Verifier can be configured _via a network protocol_, the ability to
   create Evidence about the integrity of the entity
````

Does this mean to imply that bogus policy can’t be installed by sneakernet, e.g., on a usb thumb drive??

**Comment by nedmsmith** [comment]
I don't think the 'via a network protocol' is necessary. The consideration is simply that policies have security considerations that are out of scope of the architecture.
