### ISSUE TITLE
12.1 --- Integrity at different layers

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#223]
````
   The security of conveyed information may be applied at different
   layers, whether by a conveyance protocol, or an information encoding
   format.  This architecture expects attestation messages (i.e.,
   Evidence, Attestation Results, Endorsements and Policies) are end-to-
   end protected based on the role interaction context.  For example, if
   an Attester produces Evidence that is relayed through some other
````

The first sentence seems to say ‘you can do whatever you want’, but the second seems to say “you should sign the messages”

This doesn’t seem to be about integrity; it says Evidence must be confidential.  Is that actually a requirement?

**Comment by nedmsmith** [comment]
I don't see where it says RATS messages have to be confidential. 
'end-to-end' means between RATS roles. Which can be achieved at different nesting levels; where nesting is interpreted to mean nesting in the message (data) layers. 
Summary - I don't see a problem with the proposed text.

**Comment by henkbirkholz** [comment]
I am inclined to agree with Ned here, but we could change the first line, while we're at it.

> The security protecting conveyed information may be applied at different

The reuse of the word "protected" used in the 1st sentence in the 2nd sentence

> This architecture expects attestation messages (i.e.,Evidence, Attestation Results, Endorsements and Policies) are end-to-end protected

now might make it more clear that this message protection can happen on many layers.
