### ISSUE TITLE
obscure paragraph  "Layered Attestation Environments" section

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#230]
I don't understand what this para is supposed to communicate:
```
   By definition, the Attester role creates Evidence.  An Attester may
   consist of one or more nested or staged environments, adding
   complexity to the architectural structure.  The unifying component is
   the root of trust and the nested, staged, or chained attestation
   Evidence produced.  The nested or chained structure includes Claims,
   collected by the Attester to aid in the assurance or believability of
   the attestation Evidence.
```

Also, pick one of "nested", "staged" or "chained" and drop the rest.

**Comment by henkbirkholz** [comment]
For context: this is now https://ietf-rats-wg.github.io/architecture/draft-ietf-rats-architecture.html#section-3.4
"Layered Attestation Environments"

How about this as a new starting point:

> By definition, the Attester role generates Evidence.
> An Attester may consist of one or more nested environments (layers).
> The root layers of Attesters are called roots of trust.
> A root of trust can generate Evidence, but never about itself.
> In consequence, a root of trust must be endorsed from the outside.
> Claims can be collected from or about each layer, including roots of trust.
> The corresponding claims can be structured in a nested fashion that reflects the nesting of the Attester's layers.

Effectively, I removed the last sentence, as I had a hard time to understand what it intended to add to the content here. My proposal is intended as a rework of this paragraph that goes beyond editorial changes.

**Comment by thomas-fossati** [comment]
Looks very good as a starting point.  Thanks!

**Comment by dthaler** [comment]
> How about this as a new starting point:
> 
> > By definition, the Attester role generates Evidence.
> > An Attester may consist of one or more nested environments (layers).
> > The root layers of Attesters are called roots of trust.

All good so far.

> > A root of trust can generate Evidence, but never about itself.

This sentence can be confusing, since I think it could include claims about itself in Evidence, as admitted in your point below ("Claims can be collected from or about each layer, including roots of trust.")

> > A root of trust must be endorsed from the outside.

Disagree with "must be endorsed".   Either the verifier has to trust the root of trust itself (e.g., put the root of trust's public key into its trust anchor store directly) OR must be endorsed (e.g., put the endorser's public key into the verifier's trust anchor store).

> > A root of trust in consequence can be the initial Attesting Environment in layered attestation.
> > Claims can be collected from or about each layer, including roots of trust.
> > The corresponding claims can be structured in a nested fashion that reflects the nesting of the Attester's layers.

Fine.
