### ISSUE TITLE
reduce verbosity in Section 5

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#231]
The three sentences _"There are multiple [...]"_, _"This section includes [...]"_ and _"This is not intended [...]"_ are slightly vague.  It doesn't seem to me that their information content is enough to justify them being independent sentences.
They should probably be combined.

**Comment by henkbirkholz** [comment]
OLD:

> Figure 1 shows a basic model for communication between an Attester, a Verifier, and a Relying Party. The Attester conveys its Evidence to the Verifier for appraisal, and the Relying Party gets the Attestation Result from the Verifier. There are multiple other possible models. This section includes some reference models. This is not intended to be a restrictive list, and other variations may exist.

NEW:

> Figure 1 shows a basic model for communication between an Attester, a Verifier, and a Relying Party. The Attester conveys its Evidence to the Verifier for appraisal, and the Relying Party gets the Attestation Result from the Verifier. This section introduces and names two reference models and their combined hybrid to illustrate typical variations of the basic model and to demonstrate the composability of roles defined in this document.

**Comment by thomas-fossati** [comment]
(slight refinement)

_"Figure 1 shows an abstract model for communication between an Attester, a Verifier, and a Relying Party. The Attester conveys its Evidence to the Verifier for appraisal, and the Relying Party gets the Attestation Result from the Verifier. This section refines it by describing two reference interaction schemes (topological models), as well as one possible compositions thereof.  The discussion that follows is for illustrative purposes only and does not constrain the interactions between RATS roles to the presented patterns."_

**Comment by henkbirkholz** [comment]
Reads good to me. Any other comments? (starting a virtual going once...)
