### ISSUE TITLE
Two comments on the "Passport Model" section

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#232]
1. Should this section have a forward ref to the freshness section (or otherwise discuss the freshness of the attestation results)?

2. I think that if we'd drop the paragraph below, no important information would be lost (I may be missing something but they all look like implementation details to me):
```
   There are three ways in which the process may fail.  First, the
   Verifier may refuse to issue the Attestation Result due to some error
   in processing, or some missing input to the Verifier.  The second way
   in which the process may fail is when the Attestation Result is
   examined by the Relying Party, and based upon the appraisal policy,
   the result does not pass the policy.  The third way is when the
   Verifier is unreachable.
```

**Comment by henkbirkholz** [comment]
1.) In general, all three models here have sightly varyin  freshness characteristics. I am uncertain that this is the place to discuss them. This question is similar to the lack of consistent use of freshness related terms that recently came up. Will investigate more.

2.) pulled in Dave by assigning him to this issue as I think that text was written by him. The answer here depends on scoping content for the model descriptions, too.

**Comment by dthaler** [comment]
This text is actually from @mcr who added it as part of https://github.com/ietf-rats-wg/architecture/issues/37

**Comment by dthaler** [comment]
On question 2, I would keep it since the point was to address issue 37.
On question 1, I think it's a subcase of the first way (verifier rejects because evidence isn't fresh) and a subcase of the second way (RP rejects because attestation results aren't fresh), it's not a fourth way per se.  I'd be fine with either
a) adding freshness (and a forward reference) into the "or"s of the first way, or
b) making the wording of the first way more like the wording the second way.

That is, (a)

>   There are three ways in which the process may fail.  First, the
>    Verifier may refuse to issue the Attestation Result due to some error
>    in processing, or the Evidence not being fresh (see {{freshness}}), or some missing input to the Verifier.  The second way
>    in which the process may fail is when the Attestation Result is
>    examined by the Relying Party, and based upon the appraisal policy,
>    the result does not pass the policy.  The third way is when the
>    Verifier is unreachable.

or (b)

>   There are three ways in which the process may fail.  First, the
>    Verifier may refuse to issue the Attestation Result due to the Evidence
>    not passing the Appraisal Policy for Evidence.  The second way
>    in which the process may fail is when the Attestation Result is
>    examined by the Relying Party, and based upon the Appraisal Policy for Attestation Results,
>    the result does not pass the policy.  The third way is when the
>    Verifier is unreachable.

The latter, (b), is my preference.
