### ISSUE TITLE
redundant text in the "Background Check" section

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#233]
The paragraph:
```
   Hence, the ability to let the Relying Party obtain an Attestation
   Result [...]
```
seems to reshuffle the content of the preceding one.  The two can be combined / streamlined.

**Comment by thomas-fossati** [comment]
Maybe:

_"However, like in the Passport model, an Attestation Result is still consumed by the Relying Party and so the ability to convey it in the same serialization format as the Evidence allows minimizing the code footprint and attack surface area, which is especially  important if the Relying Party is a constrained node."_

**Comment by henkbirkholz** [comment]
Personally, I like the new content here that elaborates on motivation and intent. Anyone else like to chime in here to have in impact on that expositional text?

**Comment by dthaler** [comment]
The meaning of
> _"However, like in the Passport model, an Attestation Result is still consumed by the Relying Party and so the ability to convey it in the same serialization format as the Evidence allows minimizing the code footprint and attack surface area, which is especially important if the Relying Party is a constrained node."_
is wrong, i.e., format same as the Evidence.   Instead the meaning is format same as the resource access protocol natively uses.
