### ISSUE TITLE
possible imprecision in the "Combinations" section

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#234]
We say:
```
   It is also worth pointing out that the choice of model is generally
   up to the Relying Party
```

I'm not sure it "is up to the RP"_.  Maybe better saying it "depends on the RP application" (or similar) because it's typically not a choice of the RP but of the use case / protocol flow in which the RP operates...

**Comment by henkbirkholz** [comment]
+1

**Comment by laurencelundblade** [comment]
Proposal: "Individual applications, use cases or protocol flows interacting with the same Attester can use different models."
