### ISSUE TITLE
the "Claims Encoding Formats" back-story needs some work

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#236]
This sentence:
```
   To enable remote attestation to be added to existing protocols,
   enabling a higher level of assurance against malware for example, it
   is important that information needed for appraising the Attester be
   usable with existing protocols that have constraints around what
   formats they can transport.
```
it's quite hard to digest.

But more generally, the motivating use case (OPC UA) is slightly convoluted, and I'm wondering whether it is really needed?  But assuming it were, the exposition needs to be improved to present a clear and compelling case.

**Comment by henkbirkholz** [comment]
I cannot speak for the applicability of OPC UA here. It seems to be an item in an already long list. I actually wonder more why EAP is not in there to add some diversity.

Having said that, how about:

> To enable remote attestation to be added to existing protocols, conceptual messages have to be added to the information already conveyed, sometimes in the encodings already used. The addition of RATS conceptional messages has to be realized in a way that retains their security properties. As an example, if DER-encoded X.509v3 certificates are the only message format used in a protocol, it might become necessary to embed all RATS conceptional messages in the certificates conveyed or even use the same DER-encoding the certificates are represented in.

**Comment by thomas-fossati** [comment]
Looks much better, thanks!  Elaborating a bit further:

_"Retrofitting already deployed protocols with remote attestation requires adding RATS conceptual messages to the existing data flows.  This must be done in a way that doesn't degrade the security properties of the protocol, and should use the native extension mechanisms (if available).  For example, if an authentication protocol (e.g., the TLS handshake) has to be extended with remote attestation capabilities, attestation Evidence may be embedded in an ad-hoc X.509 certificate extension, or into a new TLS Certificate Type."_

**Comment by henkbirkholz** [comment]
You had me at "retro". In my kickstarting proposal, I barged on with "DER", which is now gone but now there are TLS and Certificate Type for elaboration. None, one, or all? I don't want to overload that paragraph with arbitrary examples. Unfortunately, now these start to seem arbitrary to me. What is the reasoning for choosing examples here, actually?

**Comment by thomas-fossati** [comment]
> Unfortunately, now these start to seem arbitrary to me. What is the reasoning for choosing examples here, actually?

These are both existing mechanisms: the first (new cert extension) is [DICE](https://trustedcomputinggroup.org/wp-content/uploads/DICE-Certificate-Profiles-r01_3june2020-1.pdf), the second (new TLS cert type) is [TLS-CWT](https://datatracker.ietf.org/doc/draft-tschofenig-tls-cwt/).   I dropped DER as it's a necessity when using x.509 certs.

**Comment by henkbirkholz** [comment]
That actually helped me a lot! Maybe we should pull these reference in? I am aware that it is sometimes better to shy away from specifica, but in this case I think it would help the reader to be more specific. Thoughts?

**Comment by thomas-fossati** [comment]
Doing a background check on OP CUA, I've found that the [sec model spec](https://opcfoundation.org/developer-tools/specifications-unified-architecture/part-2-security-model/) is not open, and that there are only two research papers that talk about adding attestation to the existing model: ["Portable Trust Anchor for OPC UA Using Auto-Configuration"](https://ieeexplore.ieee.org/abstract/document/9211904) (2020) and ["Introducing remote attestation and hardware-based cryptography to OPC UA"](https://ieeexplore.ieee.org/document/8247591) (2017).  This paucity of related content makes its presence as a "demo" use case a bit brittle.  I suggest we remove it.  DICE and TLS-CWT should be enough.
