### ISSUE TITLE
connectivity from Lead Attesting Environment to sub-components

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#24]
"(via Internal Links or Network Connections)" is ambiguous.

Is it Internal (Links or Network Connections) or
(Internal Links) or (Network Connections)

**Comment by William-PanWei** [comment]
My intention is via Internal Links or via Network Connections. What I want to express is that sending the Evidence of attesters to the Lead Attester may need to use some network protocols (in the case of multi-chassis router) or not (e.g., the case of single router).

**Comment by mcr** [comment]
I think that this is well and truly dead.
