### ISSUE TITLE
Fiddling with handles

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#262]
Discuss the impact that altering the distribution of handles (e.g., delaying, suppressing) has on the security of the protocol.

Add relevant text to the Security Consideration section.

**Comment by mcr** [comment]
Is this more than just finishing #248?  If so, what?

**Comment by thomas-fossati** [comment]
the scope is different: #248 deals with the example in the appendix, this one is for text that belongs to the security considerations.
