### ISSUE TITLE
3.1. Appraisal Policies & 3.2. Reference Values now come before 4.2. Artifacts

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#264]
We underwent so much hassle, for example, to only use "Attesting Environment" after it is introduced in 3.3. for the first time.

Now, after moving the Terminology Section to 4. that kind of is pointless due to Appraisal Policies and Reference Values being used, before they are introduced for the first time.

If we want to adhere to the principle of "introduce, then use", we should fix this.

**Comment by mcr** [comment]
I believe that we discussed this on Tuesday, and we agree that forward references from Introduction and Use cases are OKAY.
