### ISSUE TITLE
use of "entity" and "Artifact" in the Terminolgy Section

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#266]
While addressing #235 I realized that I am not really happy with:

* the use of "entity" (issue). Was there a reason why we are using such a broad term here ? The term "actor" is used in other attestation-related documents. Would that be an alternative here?
* the use of "Artifacts" (nit). Used here as a section name and never again. I can see why this spawned into existence: the Artifacts Section contains Conceptual Messages, Policies, and then the term Claims. Maybe we should split this section in three?

**Comment by dthaler** [comment]
regarding artifacts, it would be odd to have a section with just one term (claims).  Maybe change "Artifacts" to "Data", which is at least used later in places like "Conceptual Data Flow"?

**Comment by mcr** [comment]
"Artifacts" -> "Conveyed Data" ?

**Comment by mcr** [comment]
Pull request for "entities" suggested, create a sample.
Do three samples.

**Comment by mcr** [comment]
closed with email in: https://mailarchive.ietf.org/arch/msg/rats/993-8As7beiuLqliXRd3-mb433U
