### ISSUE TITLE
Terminology around handles

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/architecture#291]
At IETF 110 the feedback from Russ and others was to change the term "handle" to something else.
Terms used in audio or chat included:
* Brendan: "PSK"
* mcr: "PSK generated by a third-party" 
* Hannes: "public pre-shared secret"
* Jeremy: "Pre-shared Opaque Value"

**Comment by thomas-fossati** [comment]
> At IETF 110 the feedback from Russ and others was to change the term "handle" to something else.
> Terms used in audio or chat included:
> 
> * Brendan: "PSK"
> * mcr: "PSK generated by a third-party"
> * Hannes: "public pre-shared secret"
> * Jeremy: "Pre-shared Opaque Value"

I heard "epoch id" too, which I personally like better than the above -- they all seem, for one reason or another, slightly incorrect.

**Comment by mcr** [comment]
I didn't actually like "PSK generated by a third-party", and I was probably too out of it to express my skepticism :-)
The thing that I remembered from RATS and repeated in TEEP was "Epoch Identifier".
