### ISSUE TITLE
Introduction of terms in Two Types of Environments of an Attester (3.3) section

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#298]
First mentioning of TEE, eSE, and TPM need reference in section Two Types of Environments of an Attester.

**Comment by mcr** [comment]
These terms need to have references: Trusted Execution Environments (TEEs), embedded Secure Elements (eSEs), Trusted Platform Modules (TPMs), or BIOS firmware.

**Comment by mcr** [comment]
We don't think we need to expand BIOS, and that it should be on the RFC editor Acronym list.

**Comment by mcr** [comment]
closed by #334.
