### ISSUE TITLE
Introduction of trust anchor store in Layered Attestation (3.4) section

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#299]
Does “trust anchor store” in Layered Attestation Environments require an introduction?

**Comment by laurencelundblade** [comment]
I advocate taking it out. See #293 and #294.

If / when "trust anchor store" is in the architecture document it should be in the establishment of trust in the basic non-layered Attester.  It should be somewhere in section 7.

**Comment by dthaler** [comment]
PR #336 addresses the original issue but there is more needed than just what is in PR #336 to fully address this in my view.  Two pieces remain:
1) Currently the trust anchor store is mentioned in the Verifier but not the Relying Party, and appropriate language should be updated in the Relying Party section also.
2) Unlike the TEEP architecture, the Security Consideration section focuses on the attester and so does not mention securing the trust anchor store on the Verifier and Relying Party.

**Comment by mcr** [comment]
Having merged #336, the definition of trust-anchor store definition will get moved upwards so that it can be referenced in Relying Party section, and then also a SC paragraph about securing the store.
