### ISSUE TITLE
Example for the Layered Attestation Environments (3.4) section

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#300]
The relatively abstract text in Layered Attestation Environments could really benefit from a common real world example, e.g. the thing formerly referred to as Secure Boot.

**Comment by laurencelundblade** [comment]
Are you saying that layered attestation is a form of staged boot with Verifiers on the local device? If so, Figure 3 is wrong since it doesn't show the local Verifiers.

I think it is an overreach for RATS to classify all staged boot as a form of layered Attestation. See #293.

**Comment by mcr** [comment]
The example is so long that the reader misses that it's an example, and the details are too deep.

**Comment by mcr** [comment]
The illustration is no longer an abstract example.
