### ISSUE TITLE
Confusing example in the Roles and Entities (6) section

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#302]
The example used in roles and entities actually do not illustrate two aggregated/collapsed roles that talk with each other, as they seem to be entities in two different RATS setups?

**Comment by mcr** [comment]
Agreed to delete paragraph:"For example, an entity that both connects to a wide-area network and to a system bus is taking on both the Attester and Verifier roles. As a system bus-connected entity, a Verifier consumes Evidence from other devices connected to the system bus that implement Attester roles. As a wide-area network connected entity, it may implement an Attester role."
