### ISSUE TITLE
"out-of-scope" statements scattered throughout the document

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#303]
Maybe we should add a “out of scope” summary section that provides a concise overview about the scope statements littered throughout this document?

**Comment by mcr** [comment]
This feels wrong to me.  As long as "out of scope" is searchable (i.e. we use the same word sequence), I think it is good.

**Comment by henkbirkholz** [comment]
Thanks! In other documents and also other SDOs it is considered "bad style" to chase the reader on a scavenger hunt for all scoping statements. I am agnostic to the outcome. Any other opinions?

**Comment by mcr** [comment]
I have no problem if someone wants to collect them in a section and reference back, but I would find having to read the out-of-scope section and then chase back to the place where it is relevant annoying.

**Comment by henkbirkholz** [comment]
Fine. Not sticking my head out for this one.

+1 to the label

**Comment by henkbirkholz** [comment]
The won't fix seems to represent consensus. Closing this issue.
