### ISSUE TITLE
Some redundancy in the Attester (7.2) section

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#310]
> In some cases, an attacker may be able to make inferences about the contents of attestation Evidence
> from the resulting effects or timing of the processing.
> For example, an attacker might be able to infer the value of specific Claims if it knew that only certain values were accepted by the Relying Party.

This paragraph seems to be somewhat redundant to the trust model section.

**Comment by mcr** [comment]
Reading section 7, Trust Model, it is unclear what the overlap is.
In general, if there is overlap, then I suggest just referencing it.

**Comment by mcr** [comment]
issues closed: no longer can find the redundancy.
