### ISSUE TITLE
Confusing example for time(OP) in the Events table 

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#312]
> The Relying Party performs some operation requested by the Attester.  For example, acting upon some message just received across a session created earlier at time(RA).

How is an Attester directing requests to an Relying Party? Via Evidence? I can’t really place the example; seems too abstract?

**Comment by dthaler** [comment]
> How is an Attester directing requests to an Relying Party? Via Evidence? I can’t really place the example; seems too abstract?

This is referring to normal operations discussed in the Use Cases.   So not via Evidence per se.  Via a normal protocol in the use case.
