### ISSUE TITLE
Conceptual Messages scoping contradiction

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/architecture#325]
Figure 1 (Conceptual Data Flow) has the following lines:
* Endorsements
* Reference Values
* Appraisal Policy for Evidence
* Appraisal Policy for Attestation Results
* Evidence
* Attestation Results

All of the above are conceptual messages, though only the last 2 are in scope for RATS to standardize per the current charter.

Appraisal Policies and Reference Values currently have subsections under section 3 (Architectural Overview)., whereas Endorsements, Evidence, and Attestation Results have subsections under section 8 (Conceptual Messages).

The contradiction is that section 8 is titled Conceptual Messages but does not scope itself to either (a) all lines in Figure 1, or (b) the lines in scope for standardization, and as such is inconsistent.

To fix, I think we either need to move Reference Values and the Appraisal Policies down to section 8, or else move Endorsements up to section 3.  (Or repeat some things twice, but I would not want that.)

**Comment by mcr** [comment]
Lots of support to moving Evidence to section 3.
Other solutions also considered.

**Comment by nedmsmith** [comment]
Upon review of the arch overview sections for Appraisal Policies and Reference Values sections, I think these sections should be moved to the Conceptual Messages section. But with some modification. Both sections contain a description of the message AND a description of what a conceptual message is (why we're calling it 'conceptual').
E.g. "Reference Values used in appraisal procedures come from a Reference Value Provider and are then used by the appraisal policy." describes a Reference Values conceptual message.  
While "The actual data format and semantics of any Reference Values are specific to Claims and implementations. This architecture document does not define any general purpose format for Reference Values or general means for comparison." describes the properties of a conceptual message. I've rewritten it below substituting 'conceptual message' to make the statement covering of the other messages.
"The actual data format and semantics of any conceptual message are specific to Claims and implementations. This architecture document does not define any general purpose format for conceptual messages or general means for comparison."

Under policies the following describes conceptual message properties:
"The actual data format and semantics of any Appraisal Policy is implementation specific."
New:
"The actual data format and semantics of any conceptual message is implementation specific or defined by Internet RFC".

**Comment by dthaler** [comment]
Didn't see Ned's PR until after I edited mine.  May need to merge or perhaps abandon mine.

**Comment by dthaler** [comment]
@nedmsmith please merge mine into yours if there's anything you like better, or ignore mine if you think mine should be abandoned

**Comment by mcr** [comment]
@dthaler , was there something more we needed to do to close this issue?
