### ISSUE TITLE
move section 6 before section 4.1

### ISSUE THREAD

**Issue by FrankXL** [ietf-rats-wg/architecture#34]
otherwise,  the section 4.1 including a lot of content about attester, attesting enviroment and target enviroment are not easy to understand.
Or, at least, have some general introduction or reference to section 6 about what is relation between them.

**Comment by dthaler** [comment]
Agree, Section 6 "Two Types of Environments of an Attester" gives the introduction to these terms, but they are used back in section 4.1 "Composite Attester".
Something needs to change either move section 6 up, or section 4.1 down.
