### ISSUE TITLE
Layering example

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#348]
I think the text “the read-only BIOS in this example,  has to ensure the integrity of the bootloader” is wrong since the example no longer has a “read-only BIOS” component. 

It should say “ROM” to be consistent. 

If ROM is determined to be ambiguous as a Root of Trust  and we decide to changed it to "RoT" then this sentence would be updated accordingly.

**Comment by henkbirkholz** [comment]
@nedmsmith do you want to fix this still?

**Comment by nedmsmith** [comment]
I'll add it to my list.
