### ISSUE TITLE
Ambiguous attester description in 2.7

### ISSUE THREAD

**Issue by nicopal** [ietf-rats-wg/architecture#349]
The current attester description in §2.7 is ambiguous and inconsistent with the earlier ones.
Right now it reads:  "Attester:  Every FIDO Authenticator contains an Attester."

To clarify and align the attested description with the earlier ones, I suggest replacing this text with:
"Attester component contained in a FIDO authenticator".

**Comment by nedmsmith** [comment]
Both definitions seem OK to me. The goal of the use cases isn't to provide a technical decomposition of the FIDO device IMHO. Rather, it is to provide a cursory level mapping to the abstract roles / role messages. In fact, if a change is needed I would simply have it say "Attester: FIDO Authenticator".

**Comment by nicopal** [comment]
I agree that a technical decomposition is not the goal, however the current formulation just differs too much from the other ones. The change you suggested - "Attested: FIDO Authenticator" - is a good alternative.

**Comment by mcr** [comment]
"Attester: A FIDO Authenticator".
