### ISSUE TITLE
align endorsement definitions

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#350]
In §4.2 Endorsement is defined as: _"A secure statement that an Endorser vouches for the integrity of an Attester's various capabilities such as Claims collection and Evidence signing."_

§8.2 uses a more restrictive description: _"An Endorsement is a secure statement that some entity (e.g., a manufacturer) vouches for the integrity of the device's signing capability."_, which seems to limit the scope of an Endorsement to the verification of the Attester's signature on Evidence.

I think §8.2 should be rephrased to align with §4.2 so to allow Endorsements to be more than just verification keys.

Besides, the definition of Endorser in §4.1: _"[…] Endorsements help Verifiers appraise the authenticity of Evidence"_ could be relaxed to drop the (seemingly) exclusive coupling of Endorsements with authenticity appraisal.

**Comment by nedmsmith** [comment]
"In some cases, an Endorsement is a secure statement that some entity (e.g., a manufacturer) vouches for the integrity of the device's signing capability."
