### ISSUE TITLE
RD AD review: other biometric authentication protocols

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#355]
````
** Section 2.7. Is the WG sure we need the last paragraph, "Other biometric authentication protocols ..." which cites various commercial services without citation.  Will that age well without references?  My recommendation would be to remove it.


````

**Comment by henkbirkholz** [comment]
Addressed in https://github.com/ietf-rats-wg/architecture/pull/353/commits/a0812f92af031014cf8c00a28ddbb9c0b07eeb61

**Comment by mcr** [comment]
We consider leaving IFAA in the list, if we can find a stable reference.
Wei?
If so will leave the reference in.

**Comment by William-PanWei** [comment]
I suggest just removing it. I'm not familiar with IFAA, besides that, I think the FIDO example is clear enough to show the usage of remote attestation in biometric authentication.

**Comment by mcr** [comment]
okay, removed by Henk's PR, closing.
