### ISSUE TITLE
RD AD review: are software agents okay?

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#356]
````
** Section 3.1.  
   
There is no limit to or requirement on the types
   of hardware or software environments that can be used to implement an
   Attesting Environment, for example: Trusted Execution Environments
   (TEEs), embedded Secure Elements (eSEs), Trusted Platform Modules
   (TPMs) [TCGarch], or BIOS firmware.
````
To reinforce that software only solutions are acceptable too should 'software agent' or something to that effect be added to the following example list?

**Comment by henkbirkholz** [comment]
A TEE does not function without software. I think this is good enough. Other opinions?

**Comment by mcr** [comment]
We believe that the list of comprehensive enough as it is.  If there was a good, easily recognisable example, then we would add it.

**Comment by mcr** [comment]
https://mailarchive.ietf.org/arch/msg/rats/zGTPhKrQfRfC14MTT_TKku5G5kY
