### ISSUE TITLE
RD AD: editorial comments

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#357]
`````
** Section 3.3.  Editorial. s/In consequence/Consequently,/

** Section 4.  The following terms appeared repeatedly in the document but were defined here: root of trust, target environment, and lead attester.  Should they be?

** Section 4.1. Relying Party.  Figure 1 says that the relying party also consume the "Appraisal Policy for Attestation Results" by that isn't noted here.

** Section 4.*.  Editorial.  
-- Section 4.1.  In the definition of relying party, what does the sentence fragment "Compare /relying party/ in [RFC4949]" mean?
-- Section 4.2.  Per the definition of "Claim", what does "Compare /claim/ in [RFC7519]" mean?
-- Section 4.3.  Per the definition of "Appraisal Policy for Attestation Results", what does "Compare /security policy/ in [RFC4949]" mean?

** Section 4.2.  Claim is the only definition that doesn't explicitly call out what "consumes" and "produces" it.
````

**Comment by mcr** [comment]
````
** Section 8.1.  In the spirit of inclusive terminology please use alternative phrasing for "man-in-the-middle attackers".
````

**Comment by mcr** [comment]
````
** Section 11.  Typo. s/are disclosed/is disclosed/?
````

**Comment by mcr** [comment]
````
** Section 12.1.2.1.  Editorial.

OLD
So, this is why, in general, ...

NEW
Commonly,

** Section 12.2.  Editorial.  The section title of "Integrity Protection" seems narrow given the content of this section.

````

**Comment by henkbirkholz** [comment]
Comment on Section 3.3 addressed in https://github.com/ietf-rats-wg/architecture/pull/353/commits/dfe38d917c88d9ccf342e631c4f91d6666eace8f

**Comment by henkbirkholz** [comment]
> ** Section 4.  The following terms appeared repeatedly in the document but were defined here: root of trust, target environment, and lead attester.  Should they be?

That has been a long discussion with a few hence of forth. It might look not ideal, but there was no consensus to move it to a more prominent position or even to the terminology (as it is not really a special term to this document, just a very important one). I am hesitant to touch this again. Any other thoughts?

**Comment by henkbirkholz** [comment]
> ** Section 4.1. Relying Party.  Figure 1 says that the relying party also consume the "Appraisal Policy for Attestation Results" by that isn't noted here.

Good catch. Fixed in https://github.com/ietf-rats-wg/architecture/pull/353/commits/1556f1e0ce58064437802e76daab45acf11f520d

**Comment by henkbirkholz** [comment]
> ** Section 4.*.  Editorial.  
> -- Section 4.1.  In the definition of relying party, what does the sentence fragment "Compare /relying party/ in [RFC4949]" mean?

It is meant to encourage the reader to get more context about the meaning of Relying Parties outside of the terminology specific use in this document. Should we not do this? Or should we do we do this differently? I am okay with this, I think.

**Comment by henkbirkholz** [comment]
> ** Section 4.2.  Claim is the only definition that doesn't explicitly call out what "consumes" and "produces" it.

That is intentional. It is actually the only term that is neither about a conceptual message nor a role. It still work slightly different than the encoding specific claim definitions in web tokens and belongs into the terminology. I understand that is a little bit surprising this way, but I do not see an elegant way to fix this without reducing the readability of the text. Anybody else has a proposal? Otherwise, I would leave it be.

**Comment by mcr** [comment]
Reply to items with a heart.

**Comment by mcr** [comment]
https://mailarchive.ietf.org/arch/msg/rats/zGTPhKrQfRfC14MTT_TKku5G5kY
