### ISSUE TITLE
RD AD review: reliable to be clarified

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#361]
````
** Section 8.1.
   Claims need to be
   collected in a manner that is reliable.

Can the intent of "reliable" be clarified here.
````

**Comment by nedmsmith** [comment]
This is trying say that the Target Environment can't lie to the Attesting Environment about its trustworthiness properties.

**Comment by henkbirkholz** [comment]
Spot on. A text proposal (NEW) based on Ned's comment:


> Claims need to be collected in a manner that is reliable such that a Target Environment cannot lie to the Attesting Environment about its trustworthiness properties.
