### ISSUE TITLE
RD AD review --- freshness too detailed

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#364]
** Section 10.  I found the level of detail on this section on freshness out of place and inconsistent with the level of abstraction found in the rest of the test.  In most other section, generic interaction of roles, artifacts, their associated topologies, and high level security properties was noted.  This section delves into specific implementation choices.  In particular,  Is the WG sure that it needs all of the details of Section 10.3.  Even among all of the Section in 10.*, this stands out. It doesn't seem to provide enough detail to be create interoperability but goes beyond simply introducing the concept.  Section 12.3

**Comment by nedmsmith** [comment]
I agree with the observation, but don't believe it requires any changes.

**Comment by henkbirkholz** [comment]
This was carefully discussed and weighed over the entire editorial WG phase, actually. We found delicate consensus might have resulted in an unusual high level of attention to detail, but that detailed is most certainly warranted here especially. I think the text reflects the WG consensus building in an appropriately nuanced fashion today and am very hesitant with trying to refactor it again (even if it suddenly spikes to a maybe surprising level of detail) as I deem it unlikely that it will improve by that, tbh.

**Comment by mcr** [comment]
"This section is intended for those creating protocols or solutions to understand the options available to ensure freshness"
