### ISSUE TITLE
RD AD query appraisal policy

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#365]
````
** Section 11.  Is it possible for the Appraisal Policy for Evidence to also contain
sensitive information?
````

**Comment by nedmsmith** [comment]
Yes. However, without a suitable privacy tracking identifier, it might not be possible to correlate privacy sensitive information in the policy with the actions of the Attester.

**Comment by mcr** [comment]
We should add privacy applies to appraisal policy to Privacy section.
