### ISSUE TITLE
In Section 5.2, "security policy" should be "apprisal policy"

### ISSUE THREAD

**Issue by FrankXL** [ietf-rats-wg/architecture#38]

**Comment by mcr** [comment]
>    In this model, an Attester sends Evidence to a Relying Party, which
   simply passes it on to a Verifier.  The Verifier then compares the
   Evidence against its Appraisal Policy, and returns an Attestation
   Result to the Relying Party.  The Relying Party then compares the
   Attestation Result against its own security policy.
