### ISSUE TITLE
Trust anchor definition too narrow

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/architecture#392]
Throughout the document the term "trust anchor" is meant in the [RFC6024 sense](https://www.rfc-editor.org/rfc/rfc6024.html#section-1.1) to be a public key and associated (meta)data.

This definition does not cover attestation schemes based on symmetric crypto, e.g., [TCG MARS](https://trustedcomputinggroup.org/tcg-launches-initiative-to-develop-worlds-tiniest-tpm/), [Symmetric Identity Based Device Attestation for DICE](https://trustedcomputinggroup.org/wp-content/uploads/TCG_DICE_SymIDAttest_v1_r0p94_pubrev.pdf) and Arm PSA, and should be extended to also cover such cases.

**Comment by nedmsmith** [comment]
Was there specific text that you believe needs to be changed?
