### ISSUE TITLE
The second paragraph of section 7 seems no very clear to me:

### ISSUE THREAD

**Issue by FrankXL** [ietf-rats-wg/architecture#40]
It seems to me the statement applies for both models (passport model and BC model).

**Comment by mcr** [comment]
>    In solutions following the background-check model, the Attester is
   assumed to trust the Verifier (again, whether directly or indirectly
   via a Certificate Authority that it trusts), since the Attester
   relies on an Attestation Result it obtains from the Verifier, in
   order to access resources.

This paragraph?

**Comment by FrankXL** [comment]
> > In solutions following the background-check model, the Attester is
> > assumed to trust the Verifier (again, whether directly or indirectly
> > via a Certificate Authority that it trusts), since the Attester
> > relies on an Attestation Result it obtains from the Verifier, in
> > order to access resources.
> 
> This paragraph?

yes, and my point is for both models, the Attester should also trust the Verifier. I don't see the reason why we emphasize the BC model. In other word, I think current paragraph fits for both models.

**Comment by mcr** [comment]
"There is an implicit trust that the Attester must place into the Verifier as the Attester must disclose potentially private information to the verifier in order to obtain the Attestation Results.  The Verifier may share this information with other parties, according rules that it controls"
