### ISSUE TITLE
RD AD section 5 - Topological Patterns

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#404]
related to #358 

There is something foundational I am not following about this section.  The interactions described here do not conform behaviors described in the terminology in Section 4 or the high-level reference architecture of Figure 1.  I'm not sure how to reconcile this discrepancy.  

Minimally, these discrepancies in Figure 5 and 6 are not consistent with the roles defined in Section 4.

[restated here but same feedback on -13]

-- Figure 5.  Shows the Attester consuming Attestation Results

-- Figure 5.  Shows the Attester producing Attestation Results

-- Figure 6: Shows Relying party consuming Evidence

-- Figure 6: Shows the Relying Party producing/passing Evidence

The introductory text states that "[t]he discussion that follows is for illustrative purposes only and does not constrain the interactions between RATS roles to the presented patterns."  I don't follow what is being illustrated in the context of RATS.  What is the takeaway for implementers or designers from this section?

[Author's response] https://github.com/ietf-rats-wg/architecture/issues/358

[Roman's response on -15] The above github comment addressed a few issues from the -13 review, but not this one.

**Comment by mcr** [comment]
Reply by email: "The Attester does not consume the Attestation Result, but might cache it. "

**Comment by nedmsmith** [comment]
The text explains the intent correctly regardless of how the lines are drawn. I can convince myself that it is correct draw the line through the box (or not). The important clarifying point should be that the end-to-end message flow as described in the conceptual architecture is preserved through the various topology models that may exist. Second point is there can be a large variety of topology models (aka hybrids) but none of these hybrids changes the expectation of end-to-end message flow.

**Comment by mcr** [comment]
also #415 helps.
