### ISSUE TITLE
Attesting/Target Environments terms used before being defined

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/architecture#41]
Section 6 "Two Types of Environments of an Attester" gives the introduction to these terms, but they are used back in section 4.1 "Composite Attester".

Something needs to change either move section 6 up, or section 4.1 down.

**Comment by henkbirkholz** [comment]
This seems to address the same problem as issue #34?

**Comment by dthaler** [comment]
I agree it is the same, will close this as a dup
