### ISSUE TITLE
to what extent does the security considerations talk about how long things are valid?

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#42]
TEEP and others needs to know what kind of SLA RATS can provide.

**Comment by dthaler** [comment]
The related TEEP issue is https://github.com/ietf-teep/architecture/issues/148 and an initial TEEP architecture PR is at https://github.com/ietf-teep/architecture/pull/153 which punts part of the problem to the RATS architecture, since it refers to the RATS arch for more discussion.

**Comment by dthaler** [comment]
A key architectural question is whether an attestation result may/should/must have a validity lifetime encoded in it (like DNS responses etc. have TTLs) or not.   That is, can the Verifier say that an attestation result it generates has an expiration associated?   (Physical passports and drivers licenses for example do have an expiration associated, as do X.509 certificates.)

Or is the lifetime only implementable by the Relying Party based on other information like a Timestamp in the attestation result and its own appraisal policy for attestation results?

And is there any requirement that a Relying Party and an Attestation Server need roughly synchronized clocks?  (I suspect yes.)

Offhand, I think that it would be good to allow attestation results to include an expiration timestamp.  (Aside: assuming we want EATs to be usable as attestation results, I think this also motivates adding an Expiry claim to the EAT document.)

**Comment by mingpeiwk** [comment]
I concur that a validity period should be associated with an attestation result. This is a common best practice for various assertions, certificates etc. as Dave listed.

**Comment by mcr** [comment]
I don't think that the we need to have a lifetime in the Attestation Results.  The Relying Party gets to decide if the results are fresh enough.  We have two ways to prove freshness: some kind of pronouncement of time from "above" (maybe it's GPS, I don't know) such as imagined by TUDA, or some kind of nonce-based system.
If the RP issues the nonce, it knows when it issued the nonce, so it knows how fresh the Attestation Results must be.  It also knows when it first got those results.
(Same thing applies RP->Verifier, and AttestationResults->Evidence)

**Comment by mcr** [comment]
@henkbirkholz maybe can comment.

**Comment by laurencelundblade** [comment]
EAT inherits issued-at, not-before and expiration time from CWT/JWT. There is also the nonce and the cti/jti. Note that nonce in the -03 EAT draft is an array of nonces so you can have more than one.

Lots of specific use cases will have lots of specific set ups and uses for these claims.

Seems like this is sufficient and good as far as EAT goes.

**Comment by mcr** [comment]
"Time To Live" is ambiguous, we probably need "Time of Collection" and "Time to Use" and ...

**Comment by laurencelundblade** [comment]
Time of collection is CWT "iat".

**Comment by henkbirkholz** [comment]
Attester-side:
* time of measurement
* time of collection
* time of signing/emission (isn't that iat? or does it include collection?)

RelyingParty-side:
* time of usefulness? (is this the same as the Verifier-side?)

**Comment by laurencelundblade** [comment]
Yes, 3 values possible, but was thinking collection is the same as signing, so maybe only 2. Could be handled partly by having a time stamp associated with each measurement. Not sure if CoSWID allows for that.

**Comment by laurencelundblade** [comment]
Why is time-to-live different from expiration, other than you don't know what time it is now to be able to compute the expiration.

**Comment by mcr** [comment]
a) Time(o) - Time of Value Origin       claim collected
        b) Time(x) - Value Evidence Generation. evidence generated
        b) Time(w) - Time of Collection         evidence received
        c) Time(y) - Time of Initial use        result generated
        d) Time(z) - Time of Current use        result received

**Comment by William-PanWei** [comment]
>     a) Time(o) - Time of Value Origin       claim collected
>     b) Time(x) - Value Evidence Generation. evidence generated
>     b) Time(w) - Time of Collection         evidence received
>     c) Time(y) - Time of Initial use        result generated
>     d) Time(z) - Time of Current use        result received

My suggestion:
~~~~
a) Time(o) - Time of Value Origin       claim collected
b) Time(x) - Value Evidence Generation. evidence generated
c) Time(w) - Time of Collection         evidence received
d) Time(a) - Time of Result Generation. result generated
e) Time(y) - Time of Initial use        result received
f) Time(z) - Time of Current use        current time
~~~~

**Comment by mcr** [comment]
Eric Voigt volunteered to generate a time-sequence diagram so that we can label it with o,x,w,a,y,z, etc.

**Comment by henkbirkholz** [comment]
> Why is time-to-live different from expiration, other than you don't know what time it is now to be able to compute the expiration?

TTL is typically a relative reference to points in time (the end of a duration), and expiration date is an absolute reference to a point in time (the anchored time of a period).

**Comment by laurencelundblade** [comment]
It seems like some of the times o,x,w,a,y,z are not ones that would show up in a token or a protocol.  In particular w, e and f are just times events occur at that are not recorded in either Attestation Evidence or the Attestation Result.

**Comment by nedmsmith** [comment]
Is this issue resolved by the Freshness section and appendix?

**Comment by mcr** [comment]
I believe we've hit this out of the park.
