### ISSUE TITLE
Minor grammar

### ISSUE THREAD

**Issue by steven-bellock** [ietf-rats-wg/architecture#420]
>The Relying Party role is assigned to entities that uses Attestation Results by applying its own appraisal policy to make application-specific decisions, such as authorization decisions.

should be
>The Relying Party role is assigned to entities that use Attestation Results by applying their own appraisal policies to make application-specific decisions, such as authorization decisions.

or
>The Relying Party role is assigned to an entity that uses Attestation Results by applying its own appraisal policy to make application-specific decisions, such as authorization decisions.

**Comment by nedmsmith** [comment]
I'm in favor of the second option: The Relying Party role is assigned to an entity that uses Attestation Results by applying its own appraisal policy to make application-specific decisions, such as authorization decisions.

**Comment by henkbirkholz** [comment]
I am okay with second option.
