### ISSUE TITLE
Attestation freshness / state of the attestor

### ISSUE THREAD

**Issue by steven-bellock** [ietf-rats-wg/architecture#442]
>This is essential in deciding whether the included Claims can be considered fresh, meaning they still reflect the latest state of the Attester, and that any Attestation Result was generated using the latest Appraisal Policy for Evidence, Endorsements, and Reference Values.

>Remote Attestation Procedures (RATS) enable Relying Parties to assess the trustworthiness of a remote Attester and therefore to decide whether to engage in secure interactions with it - or not.

At a high level RATS seems skewed towards a "Verify First Then Interact` model. Would the following example be consistent with RATS, or would it be considered a separate model / architecture?

1. `A` generates and stores a nonce, and then sends the nonce and a calculation request, "What is 1 + 1?", to `B`.
2.  `B` calculates `1 + 1 = 2`, and generates a signed bundle that includes the calculation request, the result, the nonce, and evidence of `B`'s state.
3. One year passes by and the state of `B` has changed.
4. `A` validates the bundle's signature, compares the bundle's nonce to `A`'s stored nonce, and verifies `B`'s evidence to conclude that `B` was in a good state when it produced the result.

In particular this is a `Interact First Then Verify` model, where the state of `B` during Step 4 is immaterial.

**Comment by thomas-fossati** [comment]
> > This is essential in deciding whether the included Claims can be considered fresh, meaning they still reflect the latest state of the Attester, and that any Attestation Result was generated using the latest Appraisal Policy for Evidence, Endorsements, and Reference Values.
> 
> > Remote Attestation Procedures (RATS) enable Relying Parties to assess the trustworthiness of a remote Attester and therefore to decide whether to engage in secure interactions with it - or not.
> 
> At a high level RATS seems skewed towards a "Verify First Then Interact` model. Would the following example be consistent with RATS, or would it be considered a separate model / architecture?
> 
> 1. `A` generates and stores a nonce, and then sends the nonce and a calculation request, "What is 1 + 1?", to `B`.
> 2. `B` calculates `1 + 1 = 2`, and generates a signed bundle that includes the calculation request, the result, the nonce, and evidence of `B`'s state.
> 3. One year passes by and the state of `B` has changed.
> 4. `A` validates the bundle's signature, compares the bundle's nonce to `A`'s stored nonce, and verifies `B`'s evidence to conclude that `B` was in a good state when it produced the result.

Note that in Step 4, to appraise `B`'s evidence, `A` needs reference values, endorsements and policy that were current at the point in time `B`'s evidence was produced.

> In particular this is a `Interact First Then Verify` model, where the state of `B` during Step 4 is immaterial.

To be valuable, appraisal needs to happen as close as possible to evidence generation.  But the actual point in time when the appraisal is conducted is not relevant, as long as all its "current" input bundle (comprising evidence, appraisal policy for evidence, reference values and endorsements) is made available to the verifier.

For this "delayed verification" use case, you probably want to have the complete appraisal input bundle to be timestamped by a trusted TSA.

**Comment by mcr** [comment]
This belongs on the list, as RFC9334 is long published.
