### ISSUE TITLE
Is there a need to have a 'basis' Topological Model?

### ISSUE THREAD

**Issue by William-PanWei** [ietf-rats-wg/architecture#50]
~~~~
+-------------+            +-------------+               +-------------+
|             |----------->|             |-------------->|             |
|   Attester  |  Evidence  |   Verifier  |  Attestation  |   Relying   |
|             |            |             |     Result    |    Party    |
+-------------+            +-------------+               +-------------+
                           Compare Evidence              Compare Attestation
                           against Appraisal             Result against
                           Policy                        Appraisal Policy
~~~~
In both the passport and background-check models, the Attester communicates directly with the Relying Party to access some resources. But in some cases, the Attester doesn't need to access resources from the Relying Party.
Assume that the Attester is a network device (router, switch, etc.), and the Relying Party is the network management system (NMS) of the network operator. In such a case, the NMS monitors the health of the device by retrieving the Attestation Result of the device from a Verifier. If the device fails the attestation process, the NMS can take countermeasures like quarantining it. So the figure above depicts this situation.

**Comment by William-PanWei** [comment]
Is this topological model covered by the passport model or background-check model?

**Comment by mcr** [comment]
The above flow is always the information flow.  The passport model and background-check are models for how the conveyance works.

**Comment by mcr** [comment]
Also, we had that diagram in the architecture documents, and we have the above diagram as figure 1 already.

**Comment by William-PanWei** [comment]
> The above flow is always the information flow. The passport model and background-check are models for how the conveyance works.

This is also a way in which the conveyance can work. I add two sentences to describe this basic one without duplicating the diagram.

**Comment by mcr** [comment]
We conclude that there is not a need for this additional topological flow.
