### ISSUE TITLE
Evidence description misses the mark

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#55]
Section 7.1 should start out with something more like "Evidence is made up of claims and usually signed by the attester"n (not signed by the device).  It should say claims are being standardized.  Should say "Evidence is always evaluated by a Verifier"

**Comment by mcr** [comment]
General agreement that we need to improve the definition to say that it is a set of claims.

**Comment by nedmsmith** [comment]
Created "Issue55" branch and pull request.

**Comment by mcr** [comment]
Issue55 merged.
