### ISSUE TITLE
Refine Implicit Trust concept in architecture document

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/architecture#59]
Current Trust Model section states:  

"a Verifier might be configured to implicitly trust firmware or even software (e.g., a hypervisor). That is, it might evaluate the trustworthiness of an application component, or operating system component or service, under the assumption that information provided about it by the lower-layer hypervisor or firmware is true. "

Would like to refine for the use of unsigned and potentially-unendorsed tokens.  If the attestation token is received over a trusted link, e.g. one that the verifier has set up with the device that is anchored in an an RoT (e.g. cellular communications link), then the verifier may implicitly trust the information sent without the evidence itself being signed.

**Comment by William-PanWei** [comment]
I didn't quite get your point. Do you mean the Attester hasn't the ability to sign the Evidence, but it can be verified by the Verifier that it has an RoT?

**Comment by mcr** [comment]
moved to #60.
