### ISSUE TITLE
Have preferred serialization formats

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/architecture#66]
For the sake of interoperability prefer some serialization formats over others. I would propose preference for CWT and JWT for Evidence and JWT for Results. This is only a preference not an exclusion of other serialization formats.

**Comment by dthaler** [comment]
Preferring JWT for Results would be incompatible with constrained Relying Parties.
We should either make no recommendation, or recommend CWT for both.

**Comment by mcr** [comment]
The architecture document should create a requirement on the protocol/use case designer to detail what formats will be used.  It should also say what constrained exist around key types, encoding, key identification.

**Comment by laurencelundblade** [comment]
On second thought, I'd be OK with removing the serialization formats section entirely or moving it to an appendix. It's an architecture document, why should it care about this particular implementation detail? Or said another way, the architecture should be neutral on serialization formats. Except for this section, it is neutral.
