### ISSUE TITLE
Class of claims for messages that 'transit' entities involved in Role interactions

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#67]
There may be a class of claims having to do with how RATS Roles convey RATS messages. This was first observed in the Composite Device where Evidence from a sub-device/sub-component 'transits' another attesting environment (aka lead Attester). 

Another pattern seems to be emerging around the various message flow models (passport, bk check, hybrid(s)) where Evidence and Attestation Results are expected to transit different entities from those implied by the Roles architecture. 

Should the architecture assert a preference for 'transited' claims as a way to flexibly attest these flows? 

Concern over whether a Relying Party is allowed to check Evidence (which isn't envisaged by the Roles arch) is easily addressed by asserting that the entity hosting the Relying Party may also host a Verifier whose sole purpose is to Verify 'transited' claims and enforce an expected message flow model such as Passport, hybrid... 

The architecture would take this approach rather than assert that implementations should invent various combinations of Evidence, AR and Endorsement with semantically important nesting conventions. 

Not sure where in the doc this type of section should go. Could be sprinkled with sections that define models and complex devices or dealt with in a separate section.

**Comment by mcr** [comment]
We believe that this has already been addressed.
Please close if you agree.
