### ISSUE TITLE
Section 4.2 and 4.3 should use similar conventions for section names and figures

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#71]
Section 4.2 / 4.3 are conceptually similar hence should follow similar conventions for naming. If section 4.3 is about "Composite Device(s)" as it relates to attestation then section 4.2 is about "Layered Device(s)" as it relates to attestation. Section names should be similar. (Artifact of having different authors maybe?)
Figure 2 caption is "Layered Attester" while Figure 3 is "Conceptual Data Flow for a Composite Device". 
It would make more sense for the section heading for 4.2 to be "Layered Device" or "Layered Device Attestation" (and "Composite Device Attestation") and figure 2 to be "Conceptual Data Flow for a Layered Device"

**Comment by William-PanWei** [comment]
I prefer "Layered Device" and "Conceptual Data Flow for a Layered Device".

**Comment by nedmsmith** [comment]
Assign this to me and I'll fix it.

**Comment by dthaler** [comment]
I would find the term "layered device" confusing.
