### ISSUE TITLE
Section 4.2 explanatory text should describe Figure 2 content

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#72]
The current Section 4.2 text details a hypothetical example aimed at providing clarity of a presumably more abstract concept. However, the concept (illustrated by figure 2) hasn't been explained.

Suggested wording:
Attestation involving a layered device involves multiple Attesting Environments that collect claims from multiple Target Environments. Attestation "layering" exists when the Target Environment contains an Attesting Environment that collects claims for the next layer Target Environment. Layering forms a cascade of target and attesting environments starting with an anchor Attesting Environment (i.e., Figure 2 - Attesting Environment A) and ending with a leaf Target Environment (i.e., Figure 2 - Target Environment C). The leaf environment isn't expected to encapsulate an Attesting Environment. Any number of layered environments (i.e., Figure 2 - Target Environment B / Attesting Environment B) could exist between the anchor and leaf. A hardware execution environment establishes trust in the anchor Attesting Environment (see Section 4.1). 

A Verifier relies on Endorsements for insight regarding trustworthiness of the anchor Attesting Environment. Verifiers may require Endorsements for all the environments. Each Attesting Environment generates Evidence for its respective Target Environment (i.e., Figure 2 - Layered Evidence for B and C). 

Layering of Evidence means the first layer Attesting Environment (i.e., Figure 2 - Attesting Environment A) integrity protects Evidence B and the next layer Attesting Environment (i.e., Figure 2 - Attesting Environment B) integrity protects Evidence C.

Note:
I stopped short of describing use of keys for integrity protection, whether or not the same or different keys can be used or where the keys are stored / protected. By inference, the attesting environments either have them locally or can use them by keyID or some other way. I also stopped short of describing how the Verifier disambiguates Evidence B from Evidence C or how each evidence instance is attributed to its proper attesting environment. If it is important to describe this then maybe more words are needed?

I think the remainder of the section could more efficiently describe the BIOS / PC boot use case relying more on the terminology in Figure 2 to describe a mapping from the abstraction in Figure 2 to an example implementation.

**Comment by mcr** [comment]
Closed in #68
