### ISSUE TITLE
What are "role compositions"?

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/architecture#73]
The introduction section uses the phrase "role compositions and data flows" then mentions "Passport Model" as an example of a role composition. 
In section 4.3 on Composite Device the second to last section describes "combinations of roles" using an example involving a Composite Device.

I think the architecture should have crisper understanding of two concepts a) "topological models" (as defined by the section 5 heading that describes Passport, BKC and Hybrid; b) "role composition" which ought to refer to the "combining of roles" by a given entity.

The terms "role composition" and "combining of roles" are too similar for them to have different meanings and "role composition" as an alias for "topological models" is unnecessary. 

I suggest pulling the second to the last paragraph in section 4.3 into a new section 4.4 titled "Role Composition" that has a paragraph defining role composition conceptually followed by the paragraph taken from section 4.3.

Suggested Text for section 4.4:
RATS roles are implemented by entities (e.g., devices). A simple realization of the architecture associates a single role to a single entity; for example, the topological models described in section 5.1 and 5.2 follow this convention. However, entities may host multiple roles as a way to accommodate more sophisticated use cases and deployment scenarios. An entity that both connects to a wide-area network and to a system bus may play both Attester and Verifier roles. As a system bus entity, a Verifier consumes Evidence from other devices connected to the system bus that implement an Attester role. As a wide-area network connected entity, it may implement an Attester role. The entity, as a system bus Verifier, may choose to fully isolate its role as a wide-area network Attester. Alternatively, attestation results might reflect an aggregation of system bus operational state claims in the form of Evidence. 

For example, in the Composite Device scenario, the lead Attester...
<paste remainder of paragraph from section 4.3>

Additionally, the introduction section should change "role composition" terminology to "topological models" as it references Passport.

**Comment by mcr** [comment]
"Role Composition" will be worked out of document.

**Comment by nedmsmith** [comment]
Also addressed in Issue55. I recommend closing this issue.

**Comment by dthaler** [comment]
"role composition" no longer appears in the doc.  I agree this can be closed.
