### ISSUE TITLE
FIXME in document

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/architecture#84]
Section 3.1 of the draft says:

>   FIXME from Henk: Measurements at early stages of
>   Layered Attestation are NOT evidence yet.
>   This text does not cover that yet

This fixme needs to be fixed somehow.

**Comment by dthaler** [comment]
There are also still statements like these in section 4.3:
> Henk: we are looking for a better term than UEFI/BIOS/Firmware

and

> [Henk: we might have to define what successful means in this example and beyond]

**Comment by dthaler** [comment]
Regarding "we are looking for a better term than UEFI/BIOS/Firmware", what do folks think about "first mutable environment"?

Example in context:
OLD: The very first Attesting Environment has to ensure the integrity of the (U)EFI / BIOS / Firmware that initially boots up a composite device (e.g.,  a cell phone).
NEW: he very first Attesting Environment has to ensure the integrity of the first mutable environment that initially boots up a composite device (e.g.,  a cell phone).

**Comment by nedmsmith** [comment]
We have a terminology convention for the thing being referred to as “UEFI/BIOS/FW/FMC etc.” called “Target Environment”. We should use our preferred abstract terminology then provide intuition in the form of examples

NEW2: The very first Attesting Environment has to ensure the integrity of the Target Environment (e.g. the BIOS, firmware or first mutable environment that initially boots up a composite device).

I don’t believe the example of a cell phone is helpful. Cell phones neither use BIOS (AFAIK) or commonly use the term ‘first mutable environment’.

**Comment by dthaler** [comment]
> We have a terminology convention for the thing being referred to as “UEFI/BIOS/FW/FMC etc.” called “Target Environment”. 

No, those terms are not synonymous.   In layered attestation, the UEFI/BIOS/firmware is also an "Attesting Environment", and software above it (or started later than it) are also Target Environments, so we cannot use the term Target Environment to mean UEFI/BIOS/firmware in general.   See PR #85 for proposed use in context.

**Comment by nedmsmith** [comment]
I agree with the text in #85 as it doesn’t use either Attesting Env or Target Env.
The issue I have with NEW is the asymmetrical use of terms “Attesting Env” and other stuff not “Target Env”. If use of Target Env is wrong then so is use of Attesting Env. The section on “Two Environments” makes these terms clear and their applicationin a Layered Device attestation also clear (in terms of cascaded measurement, attestations and executions).

Are you suggesting the resolution to #84 is to substitute with text from #85?

Thx,
Ned

**Comment by dthaler** [comment]
I believe this can be closed now that #85 is merged.
