### ISSUE TITLE
should architecture define "Attestation"

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/architecture#9]
See comments in https://github.com/ietf-rats-wg/architecture/pull/6

this term gets re-introduced here, without any annotation.
The appraisal policy are the rules on how to test the evidence.
Here, "Attestation" is the creation of the evidence
Often people use the term "Attestation" to refer to the whole process.
Suggestion that we should define this term somewhere, but maybe "Remote Attestation"?

@mcr
FIDO has NONE-Attestation-Type, where there is no assessment. TCG would call this Implicit Attestation. https://www.w3.org/TR/webauthn/#none-attestation

 @mcr
Let's take this to the WG, and maybe we can not get consensus on this term.

 @mcr
Charter says: "Remote
attestation procedures (RATS) enable relying parties to establish a level of
confidence in the trustworthiness of remote system components through the
creation of attestation evidence by remote system components and a processing
chain towards the relying party."

**Comment by dthaler** [comment]
PR #6 added a paragraph defining Remote Attestation, and PR #11 does some additional cleanup.

**Comment by dthaler** [comment]
Can we close this issue now that PR #6 and PR #11 are merged?

**Comment by henkbirkholz** [comment]
yes
