### ISSUE TITLE
Trust Model: Relying Party may require Verifier to act as Attester

### ISSUE THREAD

**Issue by gkostal** [ietf-rats-wg/architecture#92]
To establish trust in a Verifier, Section 7 states that a Relying Party may require "information" about the Verifier:
>Or, for a stronger level of security, the Relying Party might require that the Verifier itself provide information about itself that the Relying Party can use to assess the trustworthiness of the Verifier before accepting its Attestation Results

Section 7 states that an Endorser or Verifier Owner may establish trust in a Verifier by treating it as an Attester:
>The Endorser and Verifier Owner may need to trust the Verifier before giving the Endorsement and Appraisal Policy to it. Such trust can also be established directly or indirectly, implicitly or explicitly. One explicit way to establish such trust may be the Verifier first acts as an Attester and creates Evidence about itself to be consumed by the Endorser and/or Verifier Owner as the Relying Parties. If it is accepted as trustworthy, then they can provide Endorsements and Appraisal Policies that enable it to act as a Verifier.

**Topic 1: spec content.**  Why the differing levels of specifics?  Is it intentional that the methods to establish trust is different for { Endorser, Verified Owner } and the Relying Party?  I believe that the Relying Party may require Evidence from the Verifier to trust it, in fact, this is precisely how the Microsoft Azure Attestation Service (a Verifier) has been designed and implemented.

**Topic 2: conceptual dataflow diagram.**  The conceptual dataflow diagram in the architecture spec does not currently reflect that the Verifier may also be an Attester and then share Evidence with the Endorser, Verifier Owner and Relying Party.  Should it be updated?  Or have a 2nd more complex diagram?

**Topic 3: EAT.**  If accurate, I'd like to see a clear acknowledgement that the Verifier may need to act as an Attester for the Relying Party since I'd like to then see specifically how the IETF EAT specification covers this circumstance.  In other words, for an EAT that represents an AttestationResult, would the Evidence for the Verifier be embedded or discovered?  If embedded, how are submods distinguished for the Verifier's Evidence versus the AttestationResult's embedded claims, including nested EAT's?

**Comment by nedmsmith** [comment]
See inline NMS>

**Comment by mcr** [comment]
Topic 1 - Dave / LL.  Text is in wrong place.  The verifier has to trust the endorser/endorsement.
Topic 2 - Henk.

**Comment by ericvoit** [comment]
Looking at gkostal's Topic 3, I agreed with Ned that it goes beyond the original issue.  Certainly including Attester Evidence signed by Attestation Results is a valid approach.  It can significantly increase Verifier scale.   For an example see draft-voit-rats-trustworthy-path-routing-00, Section 3.5.  

But again this is mostly orthogonal to the original issue.

**Comment by gkostal** [comment]
* I've created a PR with a suggestion for specific text changes in the architecture document:  https://github.com/ietf-rats-wg/architecture/pull/110
* @mcr , thanks for filing the EAT issue.  I've added a few additional comments to that issue.

I am now OK closing this issue.
