### ISSUE TITLE
Definition of "Attester"

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#97]
~~~
Based on https://mailarchive.ietf.org/arch/msg/rats/2rwmcm7pQICXN8lzlX21lEkb9Is/
~~~

> Attester:  An entity whose attributes must be appraised in order to
> determine whether the entity is considered trustworthy, such as
> when deciding whether the entity is authorized to perform some
> operation

> Attester:
> An entity (typically a device), whose Evidence must be appraised in order to infer the extent to which the Attester is considered trustworthy, such as when deciding whether it is authorized to perform some operation

Kathleen's comment: The 'definition' seems to get into role recommendations rather than being a definition. Shouldn't this stick to what an attester is/does?

Perhaps:
> attester - entity who puts forth data that may include configuration or static system information, evidence, or claims.  The evidence may be digitally signed.

**Comment by henkbirkholz** [comment]
Evidence s created by an Attesting Environment of the Attester and must always be temper-evident (which does actually means that it must signed - but if it isn't an equivalent protection provided by a secure channel must exist).

As a first step to address "is/does". Perhaps:
> An Atterster is a target of evaluation, I think, and it is able to create Evidence about its own system characteristics.

**Comment by nedmsmith** [comment]
The way we define Evidence, it includes claims. Otherwise, the intuition is to list a set of data that (typically) represents trustworthiness attributes (which I agree with). The question I have is whether we can agree on which exemplary data to list here.

Suggest: software, configuration, initialization data (other?)

**Comment by dthaler** [comment]
In my view, the term is really something that is only relevant when the information is actually used for attestation by another entity.  Just providing the information does not make one an "attester" per se. 

Discussed in design team and a wording change was made to call it a role.
