### ISSUE TITLE
Definition of "Evidence"

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#98]
~~~
Based on https://mailarchive.ietf.org/arch/msg/rats/2rwmcm7pQICXN8lzlX21lEkb9Is/
~~~

> Evidence:  A set of information about an Attester that is to be appraised by a Verifier

Kathleen's comment: For evidence, should this definition be more about what evidence is rather than about the roles involved? The attester may not be the same component or system that attests to the evidence as well. Evidence could be measurement data, telemetry (e.g. counters on a system interface - YANG or SNMP), results of a policy comparison to configuration data).

Perhaps:
> Evidence: Information about or originating from a system/firmware/software that may include configuration data, measurements, telemetry, or inferences.

**Comment by nedmsmith** [comment]
I think attestation pertains to the claims that most directly affect trustworthiness. Since a telemetry, auditing, AV scan etc… are code that is presumed to be telling the truth, they depend on Attestation for evidence they’re valid. They are examples of what might be in a Target Environment.
