### ISSUE TITLE
Definition of "Verifier Owner" necessary?

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/architecture#99]
~~~
Based on https://mailarchive.ietf.org/arch/msg/rats/2rwmcm7pQICXN8lzlX21lEkb9Is/
~~~

Kathleen's comment: Is the following definition necessary?

> Verifier Owner:  An entity, such as an administrator, that is
> authorized to configure Appraisal Policy for Evidence in a
> Verifier

**Comment by mcr** [comment]
we will retain this definition.
